export const BACKUP_TABLES=['partners','documents','invoices','payments','sales_orders','work_orders','production_reports','spec_options','material_specs','drawings','intakes','material_drafts','number_counters','barrel_entries','barrel_audit','intake_allocations','intake_audit','drawing_specs','drawing_audit','operation_audit','audit_context'] as const;
export type BackupPayload={format:'factory-flow-backup-v1';version:string;created_at:string;tables:Record<string,Record<string,any>[]>;schema:{type:string;name:string;tbl_name:string;sql:string}[];relations:{table:string;from:string;target:string;to:string}[];files:{key:string;name:string;type:string;base64:string;sha256:string;size:number}[]};
export type Backup={payload:BackupPayload;sha256:string};
export async function digest(value:string|Uint8Array){const bytes=typeof value==='string'?new TextEncoder().encode(value):value;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource)),n=>n.toString(16).padStart(2,'0')).join('')}
export function fileReferences(tables:BackupPayload['tables']){const refs=new Map<string,{name:string;type:string}>();function walk(x:any){if(!x||typeof x!=='object')return;if(typeof x.file_key==='string'&&x.file_key)refs.set(x.file_key,{name:x.file_name||'圖檔',type:x.file_type||'application/octet-stream'});if(x.file&&typeof x.file.key==='string')refs.set(x.file.key,{name:x.file.name||'圖檔',type:x.file.type||'application/octet-stream'});for(const v of Object.values(x)){if(typeof v==='string'&&/^[\[{]/.test(v.trim())){try{walk(JSON.parse(v))}catch{}}else if(typeof v==='object')walk(v)}}walk(tables);return refs}
export async function verifyBackup(input:unknown){
 const b=input as Backup;if(!b?.payload||b.payload.format!=='factory-flow-backup-v1'||!b.sha256)throw Error('不是支援的廠務帳備份檔');
 if(await digest(JSON.stringify(b.payload))!==b.sha256)throw Error('備份檢查碼不符，檔案可能不完整或已變更');
 const p=b.payload;if(!p.tables||!Array.isArray(p.schema)||!Array.isArray(p.relations)||!Array.isArray(p.files))throw Error('備份結構不完整');
 for(const t of BACKUP_TABLES){if(!Array.isArray(p.tables[t])||!p.schema.some(s=>s.type==='table'&&s.name===t))throw Error('缺少資料表：'+t);const ids=new Set(),rowids=new Set();for(const r of p.tables[t]){if(!r||typeof r.id!=='string'||ids.has(r.id)||!Number.isSafeInteger(r.__backup_rowid)||rowids.has(r.__backup_rowid))throw Error('資料識別重複或無效：'+t);ids.add(r.id);rowids.add(r.__backup_rowid)}}
 for(const rel of [...p.relations,{table:'documents',from:'invoice_id',target:'invoices',to:'id'}]){if(!Array.isArray(p.tables[rel.table])||!Array.isArray(p.tables[rel.target]))throw Error('關聯資料表不存在');const targets=new Set(p.tables[rel.target].map(r=>r[rel.to]));for(const row of p.tables[rel.table])if(row[rel.from]!=null&&!targets.has(row[rel.from]))throw Error('資料關聯缺失：'+rel.table+'.'+rel.from)}
 const files=new Map();for(const f of p.files){if(files.has(f.key))throw Error('圖檔重複');const binary=atob(f.base64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));if(bytes.length!==f.size||await digest(bytes)!==f.sha256)throw Error('圖檔內容不完整：'+f.name);files.set(f.key,f)}
 for(const [key] of fileReferences(p.tables))if(!files.has(key))throw Error('缺少圖檔：'+key);
 return {created_at:p.created_at,version:p.version,tables:BACKUP_TABLES.map(name=>({name,count:p.tables[name].length})),files:p.files.length,rows:BACKUP_TABLES.reduce((n,t)=>n+p.tables[t].length,0)};
}
