'use client';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectTrigger,SelectItem,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
type Row=Record<string,any>;
const kinds:Record<string,string>={in:'進貨',out:'出貨',empty_in:'收空桶',empty_out:'送空桶',opening:'期初差額'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date());
export default function Barrels({partners,documents,demo,showDocument,refresh,documentId}:{partners:Row[];documents:Row[];demo:boolean;showDocument:(r:Row)=>void;refresh:()=>Promise<void>;documentId?:string}){
 const [data,setData]=useState<{entries:Row[];audit:Row[]}>({entries:[],audit:[]}),[customer,setCustomer]=useState('all'),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState(''),[form,setForm]=useState<Row|null>(null),[busy,setBusy]=useState(false),[history,setHistory]=useState<string|null>(null);
 async function load(){try{const r=await fetch('/api/barrels',{cache:'no-store'});const b=await r.json() as any;if(!r.ok)throw Error(b.error);setData(b);setError('')}catch(e){setError(String(e))}}
 useEffect(()=>{if(!demo)load()},[demo]);
 const balances:Record<string,number>={};const all:Row[]=(demo?[]:data.entries).map((e):Row=>{balances[e.customer_id]=(balances[e.customer_id]||0)+(e.voided?0:e.incoming-e.outgoing);return {...e,balance:balances[e.customer_id]}});
 const rows=all.filter(e=>(!documentId||e.document_id===documentId)&&(customer==='all'||e.customer_id===customer)&&(!from||e.date>=from)&&(!to||e.date<=to)&&`${e.number} ${e.customer} ${e.note}`.toLowerCase().includes(q.toLowerCase()));
 function open(e?:Row){if(demo)return;setForm(e?{...e,action:'edit',reason:'',request_id:crypto.randomUUID()}:{action:'manual',request_id:crypto.randomUUID(),customer_id:customer==='all'?'':customer,date:today(),kind:'empty_in',incoming:0,outgoing:0,note:'',reason:''})}
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setBusy(true);try{const r=await fetch('/api/barrels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json() as any;if(!r.ok)throw Error(b.error);setForm(null);await load();await refresh();toast.success('鐵桶帳已更新，異動紀錄已保留')}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 return <section className="panel"><div className="panel-heading"><h2>{documentId?'本單鐵桶紀錄':'客戶鐵桶往來登記簿'}</h2>{!documentId&&<Button disabled={demo} onClick={()=>open()}>新增空桶／期初登記</Button>}</div>{error&&<div className="error">{error}<Button onClick={load}>重試</Button></div>}
 {!documentId&&<div className="barrel-toolbar"><Select value={customer} onValueChange={setCustomer}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部客戶</SelectItem>{partners.filter(p=>p.kind==='customer').map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Input placeholder="搜尋單號、客戶、備註" value={q} onChange={e=>setQ(e.target.value)}/><Input aria-label="起始日期" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input aria-label="結束日期" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>}
 {customer!=='all'&&<p className="barrel-summary">目前差額：{balances[customer]||0} 桶（進入－送出；含篩選日期之前紀錄）</p>}
 <Table><TableHeader><TableRow>{['日期／客戶','類型','對應單號','進桶','出桶','客戶累計差額','備註','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(e=><TableRow key={e.id}><TableCell>{e.date}<small>{e.customer}</small></TableCell><TableCell>{kinds[e.kind]}{e.voided?'（作廢）':''}</TableCell><TableCell>{e.document_id?<button className="barrel-link" onClick={()=>{const d=documents.find(d=>d.id===e.document_id);if(d)showDocument(d);else toast.error('原單尚未載入，請重新整理')}}>{e.number}</button>:e.number}</TableCell><TableCell>{e.incoming}</TableCell><TableCell>{e.outgoing}</TableCell><TableCell>{e.balance}</TableCell><TableCell>{e.note}</TableCell><TableCell><Button variant="ghost" onClick={()=>setHistory(e.id)}>異動紀錄</Button>{!e.voided&&<Button variant="outline" onClick={()=>open(e)}>更正／作廢</Button>}</TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={8}><div className="empty-state">尚無符合的鐵桶紀錄。新進出貨單會自動帶入；舊單不推算桶數。</div></TableCell></TableRow>}</TableBody></Table>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null)}}><DialogContent className="form-dialog sm:max-w-2xl"><DialogTitle>{form?.action==='manual'?'新增鐵桶登記':'更正鐵桶紀錄'}</DialogTitle><DialogDescription>{form?.document_id?'更正桶數會同步原單；作廢會作廢整張原單。已派工進貨或已請款出貨不能作廢。':'異動前後資料都會保留。'}</DialogDescription>{form&&<form onSubmit={save}><div className="form-grid">{form.action==='manual'&&<><label className="field">客戶<Select value={form.customer_id} onValueChange={v=>setForm({...form,customer_id:v})}><SelectTrigger><SelectValue placeholder="選客戶"/></SelectTrigger><SelectContent>{partners.filter(p=>p.kind==='customer').map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label><label className="field">類型<Select value={form.kind} onValueChange={v=>setForm({...form,kind:v,incoming:0,outgoing:0})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['empty_in','empty_out','opening'].map(k=><SelectItem value={k} key={k}>{kinds[k]}</SelectItem>)}</SelectContent></Select></label></>}
 <label className="field">日期<Input required type="date" disabled={!!form.document_id} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>{['incoming','outgoing'].map(k=><label className="field" key={k}>{k==='incoming'?'進入桶數':'送出桶數'}<Input required type="number" min="0" step="1" disabled={(k==='incoming'&&['out','empty_out'].includes(form.kind))||(k==='outgoing'&&['in','empty_in'].includes(form.kind))} value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}<label className="field">備註<Input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{form.action!=='manual'&&<><label className="field">處理方式<Select value={form.action} onValueChange={v=>setForm({...form,action:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="edit">更正桶數／備註</SelectItem><SelectItem value="void">{form.document_id?'作廢整張原單及桶帳':'作廢此筆登記'}</SelectItem></SelectContent></Select></label><label className="field">修改／作廢原因 *<Input required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></>}</div><div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>取消</Button><Button disabled={busy}>{busy?'儲存中…':form.action==='void'?'確認作廢':'確認儲存'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!history} onOpenChange={v=>{if(!v)setHistory(null)}}><DialogContent className="detail-dialog"><DialogTitle>異動紀錄</DialogTitle><DialogDescription>按時間保存修改前後的桶數與原因。</DialogDescription>{data.audit.filter(a=>a.entry_id===history).map(a=>{const b=a.before?JSON.parse(a.before):null,n=JSON.parse(a.after);return <div className="barrel-audit" key={a.id}><b>{new Date(a.stamp).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {a.reason}</b><p>修改前：{b?`進 ${b.incoming}／出 ${b.outgoing}；${b.note||''}`:'新增'}</p><p>修改後：進 {n.incoming}／出 {n.outgoing}；{n.voided?'已作廢；':''}{n.note||''}</p></div>})}</DialogContent></Dialog></section>
}
