'use client';
import {DecimalInput,LeavePrompt,useUnloadGuard} from './editor-tools';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import { useState,useEffect,useRef } from 'react';
import { Plus,Copy,Trash2,Save,Layers,ArrowDown,Check } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Table,TableHeader,TableBody,TableHead,TableCell,TableRow } from '@/components/ui/table';
import { toast } from 'sonner';
import { materialKey,materialCode,type Material } from './material-types';
type Row=Omit<Material,'profile'>&{id:string;profiles:string[]};
type Series='metric'|'imperial'|'bit'|'e';
type Common={material:string;name:string;raw_length:string;style:string};
type Draft={series:Series;common:Common;selected:string[];rows:Row[]};
const emptyCommon:Common={material:'',name:'',raw_length:'',style:''};
const seriesOptions:{id:Series;label:string;name:string}[]=[{id:'metric',label:'公制 · M08–M32',name:'RS-短套'},{id:'imperial',label:'英制 · 5/16–1-1/4',name:'RS-英制短套'},{id:'bit',label:'BIT · H06–H19',name:'BIT'},{id:'e',label:'E型 · E06–E24',name:'ES-短套'}];
const integerRange=(a:number,b:number,prefix:string)=>Array.from({length:b-a+1},(_,i)=>prefix+String(a+i).padStart(2,'0'));
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;
const imperial=Array.from({length:31},(_,i)=>{const n=i+10,w=Math.floor(n/32),r=n%32,g=gcd(r,32);return !r?String(w):`${w?w+'-':''}${r/g}/${32/g}`});
const candidates:Record<Series,string[]>={metric:integerRange(8,32,'M'),imperial,bit:integerRange(6,19,'H'),e:integerRange(6,24,'E')};
function validate(r:Row){const missing:string[]=[];if(!r.material.trim())missing.push('材質');if(!r.name.trim())missing.push('品名');if(!r.drive.trim())missing.push('分');if(!r.size.trim())missing.push('尺寸');if(!r.style.trim())missing.push('型式');if(!/^\d+(\.\d+)?$/.test(r.raw_length)||Number(r.raw_length)<=0||Number(r.raw_length)>10000)missing.push('長度');if(!/^\d+(\.\d+)?$/.test(r.raw_diameter)||Number(r.raw_diameter)<=0||Number(r.raw_diameter)>10000)missing.push('外徑');if(!r.profiles.length)missing.push('孔型');return missing}
export default function BatchMaterials({open,onOpenChange,specs,draft,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;specs:{id:string;data:Material}[];draft?:{data:Draft;updated_at:string}|null;onSaved:()=>Promise<void>}){
 const [large,setLarge]=useState(false),[leave,setLeave]=useState(false),[reloadPrompt,setReloadPrompt]=useState(false),[baseline,setBaseline]=useState(''),[savedState,setSavedState]=useState<Draft|null>(null),[savedAt,setSavedAt]=useState('');
 const [series,setSeries]=useState<Series>('metric'),[common,setCommon]=useState<Common>(emptyCommon),[selected,setSelected]=useState<string[]>([]),[rows,setRowsRaw]=useState<Row[]>([]),[busy,setBusy]=useState(false),[initialized,setInitialized]=useState(false),[defaultProfiles,setDefaultProfiles]=useState(['6p']),[fillDiameter,setFillDiameter]=useState(''),[customSize,setCustomSize]=useState(''),[summary,setSummary]=useState('');
 function restore(value:Draft){setSeries(value.series);setCommon(value.common);setSelected(value.selected);setRowsRaw(value.rows);history.current=[];future.current=[];setBaseline(JSON.stringify(value))}
 useEffect(()=>{if(open&&!initialized){const initial=draft?.data||{series:'metric' as Series,common:{...emptyCommon,name:'RS-短套'},selected:[],rows:[]};restore(initial);setSavedState(draft?.data||null);setSavedAt(draft?.updated_at||'');setInitialized(true)}},[open,initialized,draft]);
 const snapshot:Draft={series,common,selected,rows};const dirty=!!baseline&&JSON.stringify(snapshot)!==baseline;useUnloadGuard(open&&dirty);
 function close(){if(busy)return;if(dirty)setLeave(true);else onOpenChange(false)}
 async function reloadDraft(){setBusy(true);try{const r=await fetch('/api/materials',{cache:'no-store'});const b=await r.json() as any;if(!r.ok)throw Error(b.error);if(!b.draft)throw Error('尚無已儲存草稿');restore(b.draft.data);setSavedState(b.draft.data);setSavedAt(b.draft.updated_at);setReloadPrompt(false);toast.success('已載入上次草稿')}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 const history=useRef<Row[][]>([]),future=useRef<Row[][]>([]),currentRows=useRef(rows);currentRows.current=rows;
 function setRows(value:Row[]|((rs:Row[])=>Row[])){const old=currentRows.current;const next=typeof value==='function'?value(old):value;history.current.push(old);if(history.current.length>100)history.current.shift();future.current=[];currentRows.current=next;setRowsRaw(next);setSummary('')}
 function undo(){const previous=history.current.pop();if(previous){future.current.push(rows);currentRows.current=previous;setRowsRaw(previous);setSummary('')}}
 function redo(){const next=future.current.pop();if(next){history.current.push(rows);currentRows.current=next;setRowsRaw(next);setSummary('')}}
 const seen=new Set(specs.map(s=>materialKey(s.data)));const duplicateKeys=new Set<string>();const expanded:Material[]=[];const statuses=rows.map(r=>{const missing=validate(r);if(missing.length)return {missing,duplicates:0,total:r.profiles.length};let duplicates=0;for(const profile of r.profiles){const data:Material={material:r.material.trim(),name:r.name.trim(),drive:r.drive.trim(),size:r.size.trim(),profile,raw_length:r.raw_length.trim(),raw_diameter:r.raw_diameter.trim(),style:r.style.trim()};const key=materialKey(data);if(seen.has(key)||duplicateKeys.has(key))duplicates++;else expanded.push(data);duplicateKeys.add(key)}return {missing,duplicates,total:r.profiles.length}});
 const incomplete=statuses.filter(x=>x.missing.length).length;const duplicateCount=statuses.reduce((s,r)=>s+r.duplicates,0);const totalCount=rows.reduce((s,r)=>s+r.profiles.length,0);
 const update=(id:string,key:keyof Row,value:any)=>{setSummary('');setRows(rs=>rs.map(r=>r.id===id?{...r,[key]:value}:r))};
 function generate(){if(!selected.length){toast.error('請先勾選實際使用的尺寸');return}if(rows.length+selected.length>100){toast.error('每份草稿最多 100 列');return}setRows(rs=>[...rs,...selected.map(size=>({id:crypto.randomUUID(),...common,drive:'1/2',size,profiles:[...defaultProfiles],raw_diameter:''}))]);setSelected([]);setSummary('');toast.success('已加入待填表格，請補上各列外徑。')}
 async function request(action:string,payload:object){const r=await fetch('/api/materials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,request_id:crypto.randomUUID(),...payload})});const result=await r.json() as {error?:string;created:number;skipped:number};if(!r.ok)throw Error(result.error);return result}
 async function saveDraft(closeAfter=false){setBusy(true);try{await request('draft',{data:snapshot});setSavedState(snapshot);setBaseline(JSON.stringify(snapshot));setSavedAt(new Date().toISOString());setLeave(false);toast.success('草稿已儲存，下次可接續填寫。');await onSaved();if(closeAfter)onOpenChange(false)}catch(e){toast.error(e instanceof Error?e.message:'草稿儲存失敗')}finally{setBusy(false)}}
 async function submit(){setBusy(true);try{const remaining={...snapshot,rows:rows.filter((_,i)=>statuses[i].missing.length)};const result=await request('batch_specs',{rows:expanded,remaining_draft:remaining});const note=`已新增 ${result.created} 筆料；略過 ${duplicateCount+result.skipped} 筆重複規格。未完成 ${remaining.rows.length} 列已留在草稿。`;restore(remaining);setSavedState(remaining);setSavedAt(new Date().toISOString());setSummary(note);toast.success(note);await onSaved()}catch(e){toast.error(e instanceof Error?e.message:'批次儲存失敗，表格內容已保留')}finally{setBusy(false)}}
 const profileChoices=['6p','12p','不適用'];
 return <><Dialog open={open} onOpenChange={v=>{if(!v)close()}}><DialogContent className={"batch-dialog editor-dialog "+(large?"editor-max":"")} onPointerDownOutside={e=>e.preventDefault()} onInteractOutside={e=>e.preventDefault()}><div className="editor-heading"><DialogTitle className="batch-title"><Layers size={24}/>快速批次建料</DialogTitle><Button variant="outline" onClick={()=>setLarge(v=>!v)}>{large?'還原視窗':'最大化'}</Button></div><DialogDescription>共同條件填一次，勾選尺寸後逐列補外徑。這裡只記錄來料特質，不綁客戶或加工圖面。</DialogDescription>
 <fieldset disabled={busy} className="batch-controls"><div className="batch-step"><span>1</span><b>選系列與共同條件</b></div><div className="batch-common"><label>系列<Select value={series} onValueChange={v=>{const next=v as Series;setSeries(next);setSelected([]);setCommon(c=>({...c,name:seriesOptions.find(s=>s.id===next)!.name}));setDefaultProfiles(next==='metric'||next==='imperial'?['6p']:['不適用'])}}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{seriesOptions.map(s=><SelectItem value={s.id} key={s.id}>{s.label}</SelectItem>)}</SelectContent></Select></label>{([['material','材質'],['name','品名'],['raw_length','來料長度（mm）'],['style','來料型式']] as [keyof Common,string][]).map(([k,label])=><label key={k}>{label}<Input value={common[k]} placeholder={k==='material'?'例如：50BV30':k==='style'?'例如：雙R角':k==='raw_length'?'例如：40':''} onChange={e=>setCommon(c=>({...c,[k]:e.target.value}))}/><button type="button" className="fill-button" disabled={!rows.length||!common[k]} onClick={()=>{setRows(rs=>rs.map(r=>({...r,[k]:common[k]})));setSummary('')}}><ArrowDown size={12}/>套用整欄</button></label>)}</div>
 <div className="batch-profiles"><b>新列孔型</b>{profileChoices.map(p=><label key={p}><Checkbox checked={defaultProfiles.includes(p)} onCheckedChange={v=>setDefaultProfiles(ps=>v?(p==='不適用'?[p]:[...ps.filter(x=>x!=='不適用'),p]):ps.filter(x=>x!==p))}/>{p==='不適用'?'不適用（BIT / E型）':p.toUpperCase()}</label>)}<small>6P＋12P 會建立兩筆料；不適用表示不使用6P／12P分類。</small></div>
 <div className="batch-step"><span>2</span><b>勾選實際使用的尺寸</b><Button type="button" variant="ghost" onClick={()=>setSelected([...candidates[series]])}>全選本系列</Button><Button type="button" variant="ghost" onClick={()=>setSelected([])}>取消勾選</Button></div><p className="batch-help">候選清單供勾選，不代表每個號數都必須使用。英制候選以 1/32 間距列出，可只勾選常用尺寸。</p>
 <div className="size-grid">{[...new Set([...candidates[series],...selected])].map(size=><label key={size} className={selected.includes(size)?'chosen':''}><Checkbox checked={selected.includes(size)} onCheckedChange={v=>setSelected(ss=>v?[...ss,size]:ss.filter(s=>s!==size))}/>{size}</label>)}</div>
 <div className="batch-generate"><div><Input aria-label="其他尺寸" placeholder="其他尺寸，例如 1-3/16" value={customSize} onChange={e=>setCustomSize(e.target.value)}/><Button type="button" variant="outline" disabled={!customSize.trim()} onClick={()=>{setSelected(ss=>[...new Set([...ss,customSize.trim()])]);setCustomSize('')}}>加入候選</Button></div><Button type="button" disabled={!selected.length||!defaultProfiles.length} onClick={generate}><Plus size={16}/>產生 {selected.length} 列草稿</Button></div>
 <div className="editor-actions"><b>整批孔型</b>{[['6p'],['12p'],['6p','12p'],['不適用']].map(ps=><Button type="button" variant="outline" key={ps.join()} disabled={!rows.length} onClick={()=>setRows(rs=>rs.map(r=>({...r,profiles:[...ps]})))}>全部 {ps.join('＋').toUpperCase()}</Button>)}</div><div className="batch-step"><span>3</span><b>補尺寸、確認入庫</b><small>可修改任一格，按 Tab 移到下一格</small><Button type="button" variant="outline" disabled={!history.current.length} onClick={undo}>復原上一步</Button><Button type="button" variant="outline" disabled={!future.current.length} onClick={redo}>重做</Button><Button type="button" variant="outline" disabled={!rows.length} onClick={()=>setRows([])}>清空表格（可復原）</Button></div><div className="batch-fill-diameter"><label>相同外徑一次填入<DecimalInput aria-label="套用外徑" placeholder="例如 22" value={fillDiameter} onChange={e=>setFillDiameter(e.target.value)}/></label><Button type="button" variant="outline" disabled={!rows.length||Number(fillDiameter)<=0||!fillDiameter} onClick={()=>setRows(rs=>rs.map(r=>({...r,raw_diameter:r.raw_diameter||fillDiameter})))}>填入空白外徑</Button><Button type="button" variant="outline" disabled={!rows.length||Number(fillDiameter)<=0||!fillDiameter} onClick={()=>setRows(rs=>rs.map(r=>({...r,raw_diameter:fillDiameter})))}>套用全部外徑</Button></div>
 <div className="batch-table"><Table><TableHeader><TableRow>{['尺寸','材質','品名','分','來料外徑','來料長度','孔型','來料型式','檢查','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,index)=><TableRow key={r.id}>{(['size','material','name','drive','raw_diameter','raw_length'] as const).map(k=><TableCell key={k}><Input aria-label={`${index+1}列 ${k}`} type="text" inputMode={k.startsWith('raw_')?'decimal':'text'} value={r[k]} onChange={e=>update(r.id,k,e.target.value)} placeholder={k==='raw_diameter'?'待填':''}/>{index===0&&rows.length>1&&<button type="button" className="fill-button" disabled={!r[k]} onClick={()=>setRows(rs=>rs.map(x=>({...x,[k]:r[k]})))}><ArrowDown size={12}/>向下填滿</button>}</TableCell>)}<TableCell><div className="row-profiles">{profileChoices.map(p=><label key={p}><Checkbox checked={r.profiles.includes(p)} onCheckedChange={v=>update(r.id,'profiles',v?(p==='不適用'?[p]:[...r.profiles.filter(x=>x!=='不適用'),p]):r.profiles.filter(x=>x!==p))}/>{p==='不適用'?'不適用':p.toUpperCase()}</label>)}</div></TableCell><TableCell><Input aria-label={`${index+1}列型式`} value={r.style} onChange={e=>update(r.id,'style',e.target.value)}/></TableCell><TableCell><details className="material-code-preview"><summary>查看料號</summary>{r.profiles.map(profile=><p key={profile}>{materialCode({...r,profile})}</p>)}</details>{statuses[index].missing.length?<span className="batch-invalid">缺：{statuses[index].missing.join('、')}</span>:statuses[index].duplicates?<span className="batch-duplicate">{statuses[index].duplicates} 筆重複，略過</span>:<span className="batch-valid"><Check size={14}/>可入庫</span>}</TableCell><TableCell><div className="batch-row-actions"><Button type="button" variant="outline" aria-label={`複製第${index+1}列`} disabled={rows.length>=100} onClick={()=>setRows(rs=>rs.flatMap(x=>x.id===r.id?[x,{...x,id:crypto.randomUUID(),profiles:[...x.profiles]}]:[x]))}><Copy size={16}/>複製這筆</Button><Button type="button" variant="ghost" size="icon" aria-label={`移除第${index+1}列`} onClick={()=>setRows(rs=>rs.filter(x=>x.id!==r.id))}><Trash2 size={16}/></Button></div></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={10}><div className="empty-state"><Layers/><b>先勾選上方尺寸，再產生草稿</b><span>外徑與長度由你填寫，系統不猜測尺寸。</span></div></TableCell></TableRow>}</TableBody></Table></div>
 </fieldset><div className="batch-bottom"><div><b>{rows.length} 列 · {totalCount} 筆規格</b><small>{savedAt?`最後暫存：${new Date(savedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}`:'尚未暫存'}{dirty?' · 有未儲存變更':''}</small><span>{expanded.length} 筆可新增 · {duplicateCount} 筆重複 · {incomplete} 列待補</span>{totalCount>100&&<span className="batch-invalid">每次最多 100 筆規格，請分批建立。</span>}{summary&&<p role="status" className="batch-valid">{summary}</p>}</div><div className="batch-footer-actions"><Button variant="outline" disabled={busy} onClick={close}>關閉</Button><Button variant="outline" disabled={busy||!savedState} onClick={()=>dirty?setReloadPrompt(true):reloadDraft()}>載入上次草稿</Button><Button variant="outline" disabled={busy} onClick={()=>saveDraft()}><Save size={16}/>暫存草稿</Button><Button disabled={busy||!expanded.length||expanded.length>100} onClick={submit}>{busy?'處理中…':`新增已完成 ${expanded.length} 筆料`}</Button></div></div><p className="batch-help">缺資料可先暫存草稿；入庫時自動產生料號，略過重複料，並將新寫法存入選項庫。相同條件的 22 / 22.0、6P / 6p 視為相同，22 與 23.5 仍是不同料。</p>
 </DialogContent></Dialog><LeavePrompt open={leave} busy={busy} onContinue={()=>setLeave(false)} onDiscard={()=>{restore(savedState||{series:'metric',common:{...emptyCommon,name:'RS-短套'},rows:[],selected:[]});setLeave(false);onOpenChange(false)}} onSave={()=>saveDraft(true)}/><AlertDialog open={reloadPrompt}><AlertDialogContent><AlertDialogTitle>載入上次草稿？</AlertDialogTitle><AlertDialogDescription>目前未儲存的變更將被取代。</AlertDialogDescription><Button variant="outline" disabled={busy} onClick={()=>setReloadPrompt(false)}>繼續編輯</Button><Button disabled={busy} onClick={reloadDraft}>確認載入</Button></AlertDialogContent></AlertDialog></>
}
