'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {DrawingFields} from './drawing-dimensions';
import {editDrawing,drawingSummary} from './drawing-types';
import {toast} from 'sonner';
type Row=Record<string,any>;
export default function DrawingManage({drawing:d,mode,raw,onClose,onSaved}:{drawing:Row;mode:'edit'|'status'|'history';raw?:Row;onClose:()=>void;onSaved:()=>Promise<void>}){const [number,setNumber]=useState(d.number),[version,setVersion]=useState(d.version),[data,setData]=useState(editDrawing(d.data)),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);const [requestId]=useState(()=>crypto.randomUUID());
 async function save(){setBusy(true);try{const r=await fetch('/api/materials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode==='edit'?'edit_drawing':'drawing_status',request_id:requestId,id:d.id,expected_revision:d.revision,reason,number,version,data,disabled:!d.disabled})}),b=await r.json() as Row;if(!r.ok)throw Error(b.error);await onSaved();toast.success('已保存並記錄異動');onClose()}catch(e){toast.error(e instanceof Error?e.message:'修改失敗')}finally{setBusy(false)}}
 const snapshot=(text:string)=>{try{const x=JSON.parse(text);return `${x.number}／${x.version}｜${x.disabled?'停用':'啟用'}｜${drawingSummary(typeof x.data==='string'?JSON.parse(x.data):x.data)}`}catch{return '紀錄無法顯示'}};
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="detail-dialog sm:max-w-4xl" onPointerDownOutside={e=>e.preventDefault()}><DialogTitle>{mode==='edit'?'修改未使用圖面':mode==='status'?(d.disabled?'重新啟用圖面':'停用圖面'):'圖面修改紀錄'}</DialogTitle><DialogDescription>{d.customer} · {d.number}／{d.version}。6P／12P 等適用來料共用這筆加工要求。</DialogDescription>{mode==='history'?<>{!(d.audit||[]).length&&<p>尚無修改或停用紀錄；此紀錄功能從本版開始。</p>}{(d.audit||[]).map((a:Row)=><section className="allocation-detail-section" key={a.id}><b>{new Date(a.stamp).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {a.action==='edit_drawing'?'修改':'狀態變更'}</b><p>人員：{(()=>{try{const actor=JSON.parse(a.actor);return actor.email||actor.id}catch{return a.actor}})()}</p><p>原因：{a.reason}</p><p>修改前：{snapshot(a.before)}</p><p>修改後：{snapshot(a.after)}</p></section>)}</>:<form onSubmit={e=>{e.preventDefault();save()}}><fieldset disabled={busy}>{mode==='edit'?<><div className="form-grid"><label className="field"><span>圖號</span><Input required value={number} onChange={e=>setNumber(e.target.value)}/></label><label className="field"><span>版本</span><Input required value={version} onChange={e=>setVersion(e.target.value)}/></label></div><DrawingFields value={data} onChange={v=>setData(editDrawing(v))} raw={raw}/><label className="field"><span>加工備註</span><Input value={data.note} onChange={e=>setData(v=>({...v,note:e.target.value}))}/></label><p>適用來料、附件及客戶保持不變；若要改適用來料或附件，請另存圖面版本。</p></>:<p>{d.disabled?'啟用後可再次選用。':'停用後不再出現在新進貨與新分配的選圖清單；既有單据仍保留原圖面。'}</p>}<label className="field"><span>修改原因 *</span><Input required maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="editor-actions"><Button variant="outline" type="button" onClick={onClose}>取消</Button><Button disabled={busy||!reason.trim()||mode==='edit'&&!!d.in_use} type="submit">確認儲存</Button></div></fieldset></form>}</DialogContent></Dialog>
}
