'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {optionValues,type CatalogSpec,type FilterKey} from './catalog-filter';
import DiameterFilter from './diameter-filter';
import {emptyDrawingPicker,sizeOptions,sizeRangeError,type DrawingPickerFilters} from './drawing-picker-filter';
export default function DrawingPickerFilterControls({value:f,onChange,specs,customer,onClear,library=false}:{library?:boolean;value:DrawingPickerFilters;onChange:(v:DrawingPickerFilters)=>void;specs:CatalogSpec[];customer:string;onClear:()=>void}){
 const [more,setMore]=useState(false),[sizeQuery,setSizeQuery]=useState('');
 const pick=(key:FilterKey,label:string)=><label className="field"><span>{label}</span><Select value={f.catalog[key]||'all'} onValueChange={v=>onChange({...f,catalog:{...f.catalog,[key]:v==='all'?'':v},...(key==='series'?{sizes:[],from:'',to:''}:{})})}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部</SelectItem>{optionValues(specs,key).map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label>;
 const sizes=sizeOptions(specs,f.catalog.series),shown=sizes.filter(s=>s.label.toLowerCase().includes(sizeQuery.trim().toLowerCase()));
 const active=Object.values(f.catalog).filter(Boolean).length+(f.diameter.op!=='all'?1:0)+(f.length.op!=='all'?1:0)+(f.sizeMode!=='all'?1:0)+(f.drawing!=='all'?1:0);
 return <div className="drawing-picker-filters"><div className="catalog-filter-grid">{pick('series','系列')}{pick('drive','分／代號')}{pick('profile','孔型')}{!library&&<label className="field"><span>該客戶圖面狀態</span><Select disabled={!customer} value={f.drawing} onValueChange={v=>onChange({...f,drawing:v as DrawingPickerFilters['drawing']})}><SelectTrigger aria-label="該客戶圖面狀態"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部</SelectItem><SelectItem value="missing">尚未建圖</SelectItem><SelectItem value="existing">已有圖面</SelectItem></SelectContent></Select>{!customer&&<small>請先選客戶</small>}</label>}</div>
 <div className="catalog-filter-grid"><DiameterFilter value={f.diameter} onChange={diameter=>onChange({...f,diameter})}/><DiameterFilter label="來料長度" placeholder="例如 40" value={f.length} onChange={length=>onChange({...f,length})}/><label className="field"><span>規格尺寸</span><Select value={f.sizeMode} onValueChange={v=>onChange({...f,sizeMode:v as DrawingPickerFilters['sizeMode']})}><SelectTrigger aria-label="尺寸篩選方式"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部尺寸</SelectItem><SelectItem value="multiple">選擇尺寸（可複選）</SelectItem><SelectItem value="range">尺寸區間（含兩端）</SelectItem></SelectContent></Select></label></div>
 {f.sizeMode==='range'&&<div className="drawing-size-range"><label className="field"><span>尺寸起</span><Input aria-label="尺寸起" placeholder={f.catalog.series==='imperial'?'5/16':'M08、H06 或 E06'} value={f.from} onChange={e=>onChange({...f,from:e.target.value})}/></label><label className="field"><span>尺寸迄</span><Input aria-label="尺寸迄" placeholder={f.catalog.series==='imperial'?'1-1/4':'M19、H19 或 E24'} value={f.to} onChange={e=>onChange({...f,to:e.target.value})}/></label>{sizeRangeError(f)&&<p className="batch-invalid" role="status">{sizeRangeError(f)}</p>}</div>}
 {f.sizeMode==='multiple'&&<div><div className="editor-actions"><Input aria-label="搜尋尺寸選項" placeholder="搜尋尺寸選項" value={sizeQuery} onChange={e=>setSizeQuery(e.target.value)} style={{maxWidth:240}}/><Button variant="outline" onClick={()=>onChange({...f,sizes:[...new Set([...f.sizes,...shown.map(s=>s.value)])]})}>勾選所列尺寸</Button><Button variant="ghost" onClick={()=>onChange({...f,sizes:[]})}>清除尺寸勾選</Button><span>已選 {f.sizes.length} 個尺寸</span></div><div className="drawing-size-options">{shown.map(s=><label key={s.value} className="drawing-check"><Checkbox checked={f.sizes.includes(s.value)} onCheckedChange={v=>onChange({...f,sizes:v?[...f.sizes,s.value]:f.sizes.filter(x=>x!==s.value)})}/>{s.label}</label>)}</div>{!f.sizes.length&&<p className="batch-invalid">請至少勾選一個尺寸</p>}</div>}
 <div className="editor-actions"><Button variant="outline" aria-expanded={more} onClick={()=>setMore(v=>!v)}>更多條件{[f.catalog.material,f.catalog.name,f.catalog.style].filter(Boolean).length?`（${[f.catalog.material,f.catalog.name,f.catalog.style].filter(Boolean).length}）`:''}</Button><Button variant="ghost" onClick={()=>{onChange(emptyDrawingPicker());setSizeQuery('');onClear()}}>{library?'清除來料條件':'清除全部條件'}{active?`（${active}）`:''}</Button></div>{more&&<div className="catalog-filter-grid">{pick('material','材質')}{pick('name','品名')}{pick('style','來料型式')}</div>}</div>
}
