import {emptyFilters,selectCatalog,seriesOf,fractionNumber,diameterMatches,noDiameter,type CatalogFilters,type CatalogSpec,type DiameterCondition} from './catalog-filter';
export type DrawingPickerFilters={catalog:CatalogFilters;diameter:DiameterCondition;length:DiameterCondition;sizeMode:'all'|'multiple'|'range';sizes:string[];from:string;to:string;drawing:'all'|'missing'|'existing'};
export const emptyDrawingPicker=():DrawingPickerFilters=>({catalog:{...emptyFilters},diameter:{...noDiameter},length:{...noDiameter},sizeMode:'all',sizes:[],from:'',to:'',drawing:'all'});
export function sizeKey(s:CatalogSpec){const series=seriesOf(s.data),n=fractionNumber(s.data.size.trim().toUpperCase());return series+':'+(Number.isFinite(n)?n:s.data.size.trim().toUpperCase())}
export function sizeOptions(specs:CatalogSpec[],series:string){const map=new Map<string,{value:string;label:string;n:number}>();for(const s of specs){if(series&&seriesOf(s.data)!==series)continue;const value=sizeKey(s),n=fractionNumber(s.data.size.trim().toUpperCase());map.set(value,{value,label:(series?'':({metric:'公制 ',imperial:'英制 ',bit:'BIT ',e:'E型 ',other:''} as Record<string,string>)[seriesOf(s.data)])+s.data.size,n})}return [...map.values()].sort((a,b)=>a.value.split(':')[0].localeCompare(b.value.split(':')[0])||(Number.isFinite(a.n)&&Number.isFinite(b.n)?a.n-b.n:a.label.localeCompare(b.label)))}
function sizeNumber(value:string,series:string){const s=value.trim().toUpperCase();const valid=series==='imperial'?/^(?:\d+[- ]+)?\d+\/\d+$|^\d+(?:\.\d+)?$/.test(s):series==='metric'?/^M?\d+(?:\.\d+)?$/.test(s):series==='bit'?/^H?\d+(?:\.\d+)?$/.test(s):series==='e'?/^E?\d+(?:\.\d+)?$/.test(s):false;return valid?fractionNumber(s):NaN}
export function sizeRangeError(f:DrawingPickerFilters){if(f.sizeMode!=='range')return '';if(!f.catalog.series||f.catalog.series==='other')return '尺寸區間請先選公制、英制、BIT 或 E 型';const from=sizeNumber(f.from,f.catalog.series),to=sizeNumber(f.to,f.catalog.series);if(!Number.isFinite(from)||!Number.isFinite(to)||from<=0||to<=0)return '請填有效的尺寸起訖值';return from>to?'尺寸下限不可大於上限':''}
export function selectDrawingMaterials(specs:CatalogSpec[],drawings:Record<string,any>[],customer:string,f:DrawingPickerFilters,query:string){
 const mapped=new Set<string>();for(const d of drawings)if(d.customer_id===customer)for(const id of [d.spec_id,...(d.spec_ids||[])])mapped.add(id);
 const invalidRange=sizeRangeError(f),from=sizeNumber(f.from,f.catalog.series),to=sizeNumber(f.to,f.catalog.series);
 return selectCatalog(specs,f.catalog,query,'size').filter(s=>diameterMatches(s.data.raw_diameter,f.diameter)&&diameterMatches(s.data.raw_length,f.length)&&(f.sizeMode==='all'||f.sizeMode==='multiple'&&f.sizes.includes(sizeKey(s))||f.sizeMode==='range'&&!invalidRange&&fractionNumber(s.data.size.trim().toUpperCase())>=from&&fractionNumber(s.data.size.trim().toUpperCase())<=to)&&(f.drawing==='all'||!!customer&&(f.drawing==='existing'?mapped.has(s.id):!mapped.has(s.id))));
}
