'use client';
import {useState,useRef,useEffect} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
export function DecimalInput(props:React.ComponentProps<typeof Input>){return <Input {...props} type="text" inputMode="decimal"/>}
export function useHistory<T>(initial:T){const [value,setValue]=useState(initial),past=useRef<T[]>([]),future=useRef<T[]>([]),current=useRef(value);current.current=value;function change(v:T|((x:T)=>T)){const next=typeof v==='function'?(v as (x:T)=>T)(current.current):v;past.current.push(current.current);if(past.current.length>100)past.current.shift();future.current=[];current.current=next;setValue(next)}function reset(v:T){past.current=[];future.current=[];current.current=v;setValue(v)}function undo(){const v=past.current.pop();if(v!==undefined){future.current.push(current.current);current.current=v;setValue(v)}}function redo(){const v=future.current.pop();if(v!==undefined){past.current.push(current.current);current.current=v;setValue(v)}}return {value,change,reset,undo,redo,canUndo:past.current.length>0,canRedo:future.current.length>0}}
export function LeavePrompt({open,busy,onContinue,onDiscard,onSave}:{open:boolean;busy:boolean;onContinue:()=>void;onDiscard:()=>void;onSave:()=>void}){return <AlertDialog open={open}><AlertDialogContent><AlertDialogTitle>尚有未儲存的變更</AlertDialogTitle><AlertDialogDescription>儲存草稿後可以下次繼續；放棄變更會回到最後儲存的內容。</AlertDialogDescription><div className="editor-actions"><Button disabled={busy} variant="outline" onClick={onContinue}>繼續編輯</Button><Button disabled={busy} variant="outline" onClick={onDiscard}>放棄變更</Button><Button disabled={busy} onClick={onSave}>{busy?'儲存中…':'儲存草稿並離開'}</Button></div></AlertDialogContent></AlertDialog>}
export function useUnloadGuard(dirty:boolean){useEffect(()=>{if(!dirty)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty])}
