'use client';
import {drawingSummary,drawingReady,drawingMatches,drawingChoice} from './drawing-types';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {materialCode,searchCode,specLabel} from './material-types';
import {toast} from 'sonner';
type Row=Record<string,any>;
export default function IntakeAllocation({intake:i,specs,drawings,onClose,onSaved}:{intake:Row;specs:Row[];drawings:Row[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[replace,setReplace]=useState(false),[query,setQuery]=useState(''),[specId,setSpecId]=useState(''),[reason,setReason]=useState(''),[drawing,setDrawing]=useState(''),[quantity,setQuantity]=useState(''),[fee,setFee]=useState(String(i.fee/100)),[due,setDue]=useState(i.due),[dispatch,setDispatch]=useState(''),[machine,setMachine]=useState(''),[operator,setOperator]=useState(''),[remove,setRemove]=useState('');
 const allocations:Row[]=i.allocations||[],allocated=allocations.reduce((n,a)=>n+a.quantity,0),legacy=!!i.dispatched&&!allocations.length,remaining=legacy?0:i.quantity-allocated;
 const choices=drawings.filter(d=>!d.disabled&&d.customer_id===i.customer_id&&drawingMatches(d,i.spec_id)).map(d=>drawingChoice(d,i.spec_id)),newSpec=specs.find(s=>s.id===specId);
 const candidates=specs.filter(s=>[s.code,searchCode(s.data),specLabel(s.data)].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 async function send(action:string,extra:Row){setBusy(true);try{const r=await fetch('/api/materials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,request_id:crypto.randomUUID(),...extra})});const b=await r.json() as Row;if(!r.ok)throw Error(b.error);await onSaved();toast.success('已儲存');if(action==='allocate')setQuantity('');if(action==='replace_material'){setReplace(false);setSpecId('');setDrawing('')}setDispatch('');setRemove('')}catch(e){toast.error(e instanceof Error?e.message:'儲存失敗')}finally{setBusy(false)}}
 const choose=(value:string,set:(v:string)=>void,label:string,items:Row[])=><Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select>;
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="detail-dialog sm:max-w-5xl" onPointerDownOutside={e=>e.preventDefault()}><DialogTitle>加工分配／修改來料</DialogTitle><DialogDescription>{i.receipt_number} · {i.customer} · {specLabel(i.material_snapshot)}</DialogDescription>
 <p><b>進貨 {i.quantity.toLocaleString()} 支 · 已分配 {legacy?i.quantity:allocated} 支 · 未分配 {remaining} 支</b></p><p>原收料 {i.packages} {i.package_unit}，加工拆分不重複計算包桶。</p>
 {!i.dispatched&&!allocations.length&&<Button variant="outline" onClick={()=>setReplace(!replace)}>修改：更換選錯的料</Button>}
 {replace&&<section className="allocation-edit"><h3>更換本筆進貨的料</h3><Input aria-label="搜尋正確料號" placeholder="搜尋 0410、M23…" value={query} onChange={e=>setQuery(e.target.value)}/>{choose(specId,setSpecId,'選擇正確的來料',candidates.map(s=>({id:s.id,label:materialCode(s.data)+' · '+s.data.style})))}{newSpec&&<p>{specLabel(newSpec.data)}；原數量及包桶保留，圖面會清空重選。</p>}<Input aria-label="更換原因" placeholder="修改原因，例如原本 KEY 錯 M22" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy||!specId||!reason.trim()||specId===i.spec_id} onClick={()=>send('replace_material',{id:i.id,spec_id:specId,expected_spec_id:i.spec_id,reason})}>確認更換料</Button></section>}
 {legacy?<p>這筆已按原方式全部派工，沿用原工單。</p>:<><Table><TableHeader><TableRow>{['圖面／完成尺寸','分配數量','單價／交期','工單／狀態','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{allocations.map(a=><TableRow key={a.id}><TableCell>{a.drawing_snapshot.number} / {a.drawing_snapshot.version}<small>{drawingSummary(a.drawing_snapshot)}</small></TableCell><TableCell>{a.quantity} 支</TableCell><TableCell>{a.fee/100} 元／支<small>{a.due}</small></TableCell><TableCell>{a.work_number||'尚未派工'}<small>{a.work_status==='completed'?'加工完成':a.work_order_id?'已派工，尚未完成':''}</small></TableCell><TableCell>{!a.work_order_id&&<><Button disabled={busy} onClick={()=>setDispatch(a.id)}>派工</Button><Button variant="ghost" disabled={busy} onClick={()=>setRemove(a.id)}>取消分配</Button></>}</TableCell></TableRow>)}</TableBody></Table>
 {dispatch&&<section className="allocation-edit"><h3>派工：{allocations.find(a=>a.id===dispatch)?.quantity} 支</h3><Input aria-label="機台" placeholder="機台（可留空）" value={machine} onChange={e=>setMachine(e.target.value)}/><Input aria-label="操作人員" placeholder="師傅 *" value={operator} onChange={e=>setOperator(e.target.value)}/><Button disabled={busy||!operator.trim()} onClick={()=>send('dispatch_allocation',{id:dispatch,machine,operator,start:true})}>派工並開工</Button><Button variant="ghost" onClick={()=>setDispatch('')}>取消</Button></section>}
 {remaining>0&&<section className="allocation-edit"><h3>新增加工分配</h3>{choose(drawing,setDrawing,'選擇本次加工圖面',choices.map(d=>({id:d.id,label:`${d.number} / ${d.version} · ${drawingSummary(d.data)}`})))}{drawing&&!drawingReady(choices.find(d=>d.id===drawing)?.data)&&<p role="alert">所選圖面兩端尚待確認，請確認後另存版本再分配。</p>}{!choices.length&&<p>請先到「加工圖面庫」，為本客戶與這筆來料建立圖面。</p>}<div className="form-grid"><label className="field"><span>本次分配數量（支）</span><Input inputMode="numeric" value={quantity} onChange={e=>setQuantity(e.target.value)}/><Button variant="ghost" onClick={()=>setQuantity(String(remaining))}>填入剩餘 {remaining} 支</Button></label><label className="field"><span>加工單價（元／支）</span><Input inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)}/></label><label className="field"><span>交期</span><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><Button disabled={busy||!drawing||!drawingReady(choices.find(d=>d.id===drawing)?.data)||!/^\d+$/.test(quantity)||Number(quantity)<=0||Number(quantity)>remaining||!/^\d+(\.\d+)?$/.test(fee)||!due||due<i.date} onClick={()=>send('allocate',{id:i.id,drawing_id:drawing,quantity:Number(quantity),fee:Number(fee),due})}>儲存這筆分配</Button><p>可連續新增不同圖面；尚未派工的分配可取消後重新填寫。</p></section>}</>}
 {!!i.audit?.length&&<details><summary>來料修改紀錄（{i.audit.length}）</summary>{i.audit.map((a:Row)=><p key={a.id}>{new Date(a.stamp).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {a.reason}<br/>{specLabel(JSON.parse(a.before))} → {specLabel(JSON.parse(a.after))}<br/>操作帳號：{(()=>{try{const actor=JSON.parse(a.actor);return actor.email||actor.id}catch{return a.actor}})()}</p>)}</details>}
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove('')}}><AlertDialogContent><AlertDialogTitle>取消這筆加工分配？</AlertDialogTitle><AlertDialogDescription>數量會回到未分配，原進貨數量與包桶保持不變。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>返回</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>send('remove_allocation',{id:remove})}>確認取消分配</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </DialogContent></Dialog>
}
