'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {uncutLength} from './uncut-length';
import SocketDiagram from './socket-diagram';
import LabelBarcode from './label-barcode';
import {grooveSummary,grooveError} from './groove-types';
import {endSummary,drawingReady} from './drawing-types';
type Row=Record<string,any>;
const defaults={width:'82',height:'121',x:'0',y:'0'};
export const labelCSS=`*{box-sizing:border-box}.job-label-paper{background:white;color:black;font-family:Arial,"Microsoft JhengHei",sans-serif;font-size:9pt;line-height:1.22;padding:3mm;overflow:hidden}.job-label-paper header{border-bottom:.3mm solid black;padding-bottom:1mm}.job-label-paper h2{font-size:13pt;margin:1mm 0}.job-label-paper h3{font-size:11pt;margin:1mm 0}.job-label-paper p{margin:1mm 0;overflow-wrap:anywhere}.job-label-paper .socket-diagram{display:block;width:100%;height:40mm;margin:1mm 0}.label-dimensions{border-top:.25mm solid black;border-bottom:.25mm solid black;padding:1mm 0}.label-quantity{font-size:12pt;font-weight:bold;padding:1mm 0}.label-meta{font-size:8pt}.label-barcode{display:block;width:100%;height:8mm;margin-top:1mm}.label-warning{font-weight:bold;border:.5mm solid black;padding:1mm}.label-pattern{font-weight:bold;font-size:11pt}.label-note{white-space:pre-wrap}`;
export function JobLabelPaper({job:j,width,height,paperRef}:{job:Row;width:number;height:number;paperRef?:React.Ref<HTMLDivElement>}){const d=j.drawing_snapshot,m=j.material_snapshot||{},g=d?.groove;return <div ref={paperRef} className="job-label-paper" style={{width:width+'mm',height:height+'mm'}}><header><p>客戶：{j.customer}</p><h2>{m.drive?`${m.drive} × ${m.size} × ${m.profile}`:j.product}</h2><div className="label-pattern">{d?.operation_code?`${d.operation_code}${d.operation_code==='F'?' 車修雙頭':''}｜`:''}{g?.kind==='none'?'無溝':g?.kind==='round'?'圓一溝':g?.kind==='custom'?g.name:'溝槽待確認'}</div></header>{(!drawingReady(d)||!g||g.kind==='pending')&&<p className="label-warning">資料待確認，勿依此加工</p>}<SocketDiagram drawing={d} raw={m}/><div className="label-dimensions"><p><b>完成總長 {d?.length||'待確認'} mm</b>　公差 {d?.length_tolerance||'待確認'}</p><p>{d?.ends?.drive?.mode==='machine'?'4R 方孔端':'方孔端'}：{endSummary(d?.ends?.drive)}{uncutLength(d,'drive')!==null?`；未加工長度 ${uncutLength(d,'drive')} mm`:''}</p><p>工作端：{endSummary(d?.ends?.work)}</p>{g?.kind!=='none'&&<p>{grooveSummary(g)}</p>}</div><div className="label-quantity">本次加工 {Number(j.quantity).toLocaleString('zh-TW')} 支<br/>來料總數 {j.intake_quantity==null?'未記錄':Number(j.intake_quantity).toLocaleString('zh-TW')+' 支'}</div><div className="label-meta"><p>來料 Ø{m.raw_diameter||'—'} × {m.raw_length||'—'}L｜{m.material||'—'}</p><p>進貨：{j.receipt_number||'—'}</p><p>圖號／版本：{d?.number||'待確認'}／{d?.version||'—'}</p>{d?.note&&<p className="label-note">特殊要求：{d.note}</p>}<p>派工：{j.number}</p></div><LabelBarcode value={j.number}/></div>}
export default function JobLabel({job,onClose}:{job:Row;onClose:()=>void}){const [fields,setFields]=useState(defaults),[overflow,setOverflow]=useState(false),[printing,setPrinting]=useState(false);const paper=useRef<HTMLDivElement>(null);const settings={width:Number(fields.width),height:Number(fields.height),x:Number(fields.x),y:Number(fields.y)};
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('factory-label-printer')||'null');if(s&&s.width>=50&&s.width<=150&&s.height>=80&&s.height<=300&&Math.abs(s.x)<=10&&Math.abs(s.y)<=10)setFields({width:String(s.width),height:String(s.height),x:String(s.x),y:String(s.y)})}catch{}},[]);
 useEffect(()=>{const el=paper.current;if(!el)return;const check=()=>setOverflow(el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1);const observer=new ResizeObserver(check);observer.observe(el);check();return ()=>observer.disconnect()},[fields,job]);
 const valid=Object.values(fields).every(v=>v.trim()!==''&&Number.isFinite(Number(v)))&&Number.isFinite(settings.width)&&settings.width>=50&&settings.width<=150&&settings.height>=80&&settings.height<=300&&Math.abs(settings.x)<=10&&Math.abs(settings.y)<=10;
 async function print(){if(!paper.current||!valid||overflow)return;setPrinting(true);try{try{localStorage.setItem('factory-label-printer',JSON.stringify(settings))}catch{}const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;top:0;width:900px;height:1200px';document.body.appendChild(frame);const win=frame.contentWindow;if(!win)throw Error('無法開啟列印');const doc=win.document;doc.open();doc.write('<!doctype html><html lang="zh-Hant"><head><title>派工標籤</title><style>'+labelCSS+`@page{size:${settings.width}mm ${settings.height}mm;margin:0}html,body{margin:0;padding:0;background:white}.job-label-paper{transform:translate(${settings.x}mm,${settings.y}mm);print-color-adjust:exact}</style></head><body>`+paper.current.outerHTML+'</body></html>');doc.close();await doc.fonts.ready;await new Promise(r=>setTimeout(r,100));win.addEventListener('afterprint',()=>frame.remove(),{once:true});win.focus();win.print();setTimeout(()=>frame.remove(),120000)}catch(e){toast.error(e instanceof Error?e.message:'列印失敗')}finally{setPrinting(false)}}
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="detail-dialog label-dialog" onPointerDownOutside={e=>e.preventDefault()}><DialogTitle>派工標籤預覽</DialogTitle><DialogDescription>以這張工單保存的圖面版本列印。本次加工／來料總數與包桶數無關。</DialogDescription><div className="label-settings">{[['width','紙寬（mm）'],['height','紙高（mm）'],['x','左右偏移（mm）'],['y','上下偏移（mm）']].map(([k,t])=><label className="field" key={k}><span>{t}</span><Input type="text" inputMode="decimal" value={fields[k as keyof typeof fields]} onChange={e=>setFields(s=>({...s,[k]:e.target.value}))}/></label>)}</div><p>列印請選相同紙張尺寸、縮放 100%、關閉頁首頁尾。偏移正值往右／往下，會影響紙邊；首次請試印一張。</p>{!valid&&<p role="alert">紙寬限 50–150 mm，紙高 80–300 mm；偏移限 ±10 mm。</p>}{overflow&&<p className="batch-invalid" role="alert">內容超出紙張，請增加紙高；不會裁掉尺寸後直接列印。</p>}<style>{labelCSS}</style><div className="label-preview"><JobLabelPaper job={job} width={valid?settings.width:82} height={valid?settings.height:121} paperRef={paper}/></div><div className="editor-actions"><Button variant="outline" onClick={()=>setFields(defaults)}>還原 82 × 121</Button><Button disabled={!valid||overflow||printing} onClick={print}>{printing?'準備列印…':'列印這張標籤'}</Button></div></DialogContent></Dialog>
}
