'use client';
import { useEffect, useState, useCallback } from 'react';
import { Plus, Search, ClipboardList, Play, Pause, CheckCheck, Truck, UserRound, Factory, Printer, ArrowUpRight, PackageCheck, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import JobLabel from './job-label';
import {DrawingDimensions} from './drawing-dimensions';

type Partner={id:string;name:string;kind:string};
type Order={id:string;number:string;partner_id:string;customer:string;date:string;due:string;product:string;spec:string;quantity:number;unit:string;price:number;note:string;work_order_id:string|null;work_number?:string;work_status?:string;good?:number;shipped?:number};
type Job={id:string;number:string;order_id:string;order_number:string;customer:string;partner_id:string;product:string;spec:string;quantity:number;unit:string;price:number;due:string;order_note:string;machine:string;operator:string;status:string;good:number;defective:number;shipped:number;started_at:string|null;completed_at:string|null;material_snapshot?:Record<string,string>;drawing_snapshot?:Record<string,string>;receipt_number?:string};
type Report={id:string;work_order_id:string;reported_at:string;operator:string;good:number;defective:number;note:string};
type ProductionData={orders:Order[];jobs:Job[];reports:Report[]};
type Form={barrels:number;packages:number;package_unit:string;request_id:string;id:string;order_id:string;partner_id:string;date:string;due:string;product:string;spec:string;quantity:number;unit:string;price:number;note:string;machine:string;operator:string;good:number;defective:number;tax_rate:number};
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fmt=(n:number)=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2}).format(n);
const amount=(n:number)=>fmt(n/100);
const timestamp=(v:string|null)=>v?new Date(v).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'尚未記錄';
const statusLabel:Record<string,string>={pending:'待開工',running:'加工中',paused:'已暫停',completed:'已完工'};
const nothing:ProductionData={orders:[],jobs:[],reports:[]};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function initialForm():Form{return {barrels:0,packages:1,package_unit:'包',request_id:crypto.randomUUID(),id:'',order_id:'',partner_id:'',date:day(),due:day(),product:'',spec:'',quantity:1,unit:'支',price:0,note:'',machine:'',operator:'',good:0,defective:0,tax_rate:5}}
function example():ProductionData {
 const a:Order={id:'so-demo-1',number:'SO-示範-001',partner_id:'p1',customer:'宏盛工具股份有限公司',date:day(),due:day(),product:'1/2 六角套筒',spec:'17 mm・50BV30',quantity:10000,unit:'支',price:1200,note:'依圖面加工，良品數達標後完工。',work_order_id:'wo-demo-1',work_number:'WO-示範-001',work_status:'running',good:3600,shipped:0};
 const b:Order={...a,id:'so-demo-2',number:'SO-示範-002',partner_id:'p2',customer:'永信精密工業',product:'長套筒',spec:'21 mm',quantity:2000,price:1800,work_order_id:null,work_number:undefined,work_status:undefined,good:0};
 const c:Order={...a,id:'so-demo-3',number:'SO-示範-003',product:'六角套筒',spec:'14 mm',quantity:5000,work_order_id:'wo-demo-2',work_number:'WO-示範-002',work_status:'completed',good:5000,shipped:2000};
 const make=(o:Order,machine:string,operator:string,defective:number):Job=>({id:o.work_order_id!,number:o.work_number!,order_id:o.id,order_number:o.number,customer:o.customer,partner_id:o.partner_id,product:o.product,spec:o.spec,quantity:o.quantity,unit:o.unit,price:o.price,due:o.due,order_note:o.note,machine,operator,status:o.work_status!,good:o.good||0,defective,shipped:o.shipped||0,started_at:day()+'T00:00:00Z',completed_at:o.work_status==='completed'?day()+'T04:00:00Z':null});
 return {orders:[b,a,c],jobs:[make(a,'車床 02','阿明',40),make(c,'車床 01','志成',15)],reports:[{id:'demo-report',work_order_id:'wo-demo-1',reported_at:day()+'T03:00:00Z',operator:'阿明',good:3600,defective:40,note:'首件確認完成，正常生產。'},{id:'demo-report-2',work_order_id:'wo-demo-2',reported_at:day()+'T04:00:00Z',operator:'志成',good:5000,defective:15,note:'完工待出貨。'}]};
}
export default function Production({view,demo,partners,onShip,navigate}:{view:'orders'|'production';demo:boolean;partners:Partner[];onShip:()=>Promise<void>;navigate:(v:string)=>void}){
 const [labelJob,setLabelJob]=useState<Job|null>(null);
 const [data,setData]=useState<ProductionData>(nothing),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[modal,setModal]=useState(''),[form,setForm]=useState<Form|null>(null),[busy,setBusy]=useState(false),[activeId,setActiveId]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/production',{cache:'no-store'});const body=await r.json() as ProductionData & {error?:string};if(!r.ok)throw Error(body.error);setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'載入失敗')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!demo)load()},[demo,load]);
 useEffect(()=>{setFilter('all');setQuery('');setModal('');if(view==='orders')setActiveId(null)},[view,demo]);
 useEffect(()=>{setActiveId(null)},[demo]);
 const current=demo?example():data;
 const active=current.jobs.find(j=>j.id===activeId);
 const selectedJob=form?current.jobs.find(j=>j.id===form.id):undefined;
 const planned=current.orders.filter(o=>!o.work_order_id);
 const running=current.jobs.filter(j=>j.status==='running');
 const ready=current.jobs.filter(j=>j.status==='completed'&&j.shipped<j.good);
 const overdue=current.jobs.filter(j=>j.status!=='completed'&&j.due<day());
 function open(type:string,overrides:Partial<Form>={}){if(demo){toast.info('示範模式僅供預覽，請切回正式作業。');return}setForm({...initialForm(),...overrides});setModal(type)}
 const change=<K extends keyof Form>(k:K,value:Form[K])=>setForm(f=>f?{...f,[k]:value}:f);
 async function mutate(payload:Record<string,unknown>){const r=await fetch('/api/production',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json() as {ok?:boolean;id?:string;error?:string};if(!r.ok)throw Error(body.error);return body;}
 async function submit(e:React.FormEvent){e.preventDefault();if(!form||busy)return;setBusy(true);try{await mutate({...form,action:modal});setModal('');toast.success(modal==='ship'?'已建立出貨單，可至出貨管理請款。':'已儲存');await load();if(modal==='ship')await onShip();}catch(e){toast.error(e instanceof Error?e.message:'儲存失敗，請重試')}finally{setBusy(false)}}
 async function state(job:Job,next:string){if(demo){toast.info('請切回正式作業操作工單。');return}setBusy(true);try{await mutate({action:'state',id:job.id,state:next,barrels:0,packages:1,package_unit:'包',request_id:crypto.randomUUID()});toast.success(next==='running'?'已開工':next==='paused'?'已暫停':'已完工，可建立出貨單');await load()}catch(e){toast.error(e instanceof Error?e.message:'操作失敗')}finally{setBusy(false)}}
 function jobStatus(j:Job){return <span className={'status '+(j.status==='running'?'active-status':j.status==='completed'?'done':j.status==='paused'?'paused-status':'wait')}>{statusLabel[j.status]}</span>}
 const matches=(values:unknown[])=>values.join(' ').toLowerCase().includes(query.trim().toLowerCase());
 const orders=current.orders.filter(o=>matches([o.number,o.customer,o.product,o.spec])&&(filter==='all'||(filter==='pending'?!o.work_order_id:!!o.work_order_id)));
 const jobs=current.jobs.filter(j=>matches([j.number,j.order_number,j.customer,j.product,j.machine,j.operator])&&(filter==='all'||j.status===filter));
 return <div className="production-space">{labelJob&&<JobLabel job={labelJob} onClose={()=>setLabelJob(null)}/>}<div className="production-summary"><button onClick={()=>{navigate('production');setFilter('pending')}}><span>待開工工單</span><b>{current.jobs.filter(j=>j.status==='pending').length}<small>張</small></b><ClipboardList/></button><button onClick={()=>{navigate('production');setFilter('running')}}><span>加工中的工單</span><b>{running.length}<small>張</small></b><Factory/></button><div><span>完工待出貨</span><b>{ready.length}<small>張</small></b><PackageCheck/></div><div><span>超過交期未完工</span><b className="orange">{overdue.length}<small>張</small></b><Clock/></div></div>
 {!demo&&error&&<div className="error" role="alert">{error}<Button variant="outline" onClick={load}>重試</Button></div>}
 <section className="panel"><div className="panel-heading"><div><h2>{view==='orders'?'客戶訂單':'生產工單'}</h2><span>{view==='orders'?orders.length:jobs.length} 筆資料</span></div>{view==='orders'?<Button onClick={()=>open('order')}><Plus size={17}/>新增訂單</Button>:<Button onClick={()=>navigate('in')}><Plus size={17}/>從來料派工</Button>}</div><div className="toolbar production-toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">全部</TabsTrigger>{view==='orders'?<><TabsTrigger value="pending">待開工單</TabsTrigger><TabsTrigger value="created">已開工單</TabsTrigger></>:Object.entries(statusLabel).map(([v,l])=><TabsTrigger value={v} key={v}>{l}</TabsTrigger>)}</TabsList></Tabs><div className="search"><Search size={17}/><Input aria-label="搜尋訂單與工單" value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='orders'?'搜尋訂單、客戶、品名':'搜尋工單、機台、人員、品名'}/></div></div>
 {!demo&&loading?<div className="empty-state" role="status">正在讀取生產資料…</div>:view==='orders'?<Table><TableHeader><TableRow>{['訂單 / 客戶','品名 / 規格','訂單數量','單價（未稅）','交期','生產進度','操作'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{orders.map(o=><TableRow key={o.id}><TableCell><strong className="number">{o.number}</strong><small>{o.customer}</small></TableCell><TableCell><b>{o.product}</b><small>{o.spec||'—'}</small></TableCell><TableCell className="money">{fmt(o.quantity)} {o.unit}</TableCell><TableCell>$ {amount(o.price)}</TableCell><TableCell>{o.due}</TableCell><TableCell><span className={'status '+(o.work_order_id?'done':'wait')}>{o.work_order_id?statusLabel[o.work_status||'pending']:'待開工單'}</span>{o.work_number&&<small>{o.work_number}</small>}</TableCell><TableCell>{o.work_order_id?<Button variant="ghost" onClick={()=>{navigate('production');setActiveId(o.work_order_id)}}>查看工單 <ArrowUpRight size={15}/></Button>:<Button variant="outline" onClick={()=>open('work_order',{order_id:o.id})}>開立工單</Button>}</TableCell></TableRow>)}{!orders.length&&<TableRow><TableCell colSpan={7}><div className="empty-state"><ClipboardList size={30}/><b>{query?'沒有符合的訂單':'還沒有這類訂單'}</b><span>先建立客戶訂單，再開立工單與派工。</span><Button variant="outline" onClick={()=>open('order')}>新增訂單</Button></div></TableCell></TableRow>}</TableBody></Table>:<Table><TableHeader><TableRow>{['工單 / 客戶','品名 / 交期','機台 / 人員','良品進度','不良數','狀態','操作'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{jobs.map(j=><TableRow key={j.id}><TableCell><strong className="number">{j.number}</strong><small>{j.customer}</small></TableCell><TableCell><b>{j.product}</b><small className={j.due<day()&&j.status!=='completed'?'late-date':''}>{j.spec} · {j.due}</small></TableCell><TableCell><span>{j.machine||'尚未派工'}</span><small>{j.operator||'未指定人員'}</small></TableCell><TableCell><div className="production-progress"><b>{fmt(j.good)} <span>/ {fmt(j.quantity)} {j.unit}</span></b><Progress value={j.good/j.quantity*100} aria-label={`良品完成 ${Math.round(j.good/j.quantity*100)}%`}/><small>還需 {fmt(j.quantity-j.good)} {j.unit}</small></div></TableCell><TableCell>{fmt(j.defective)}</TableCell><TableCell>{jobStatus(j)}</TableCell><TableCell><Button variant="outline" onClick={()=>setActiveId(j.id)}>操作 / 明細</Button></TableCell></TableRow>)}{!jobs.length&&<TableRow><TableCell colSpan={7}><div className="empty-state"><Factory size={30}/><b>目前沒有符合的工單</b><span>到進貨管理確認來料圖面，點「派工」即可建立工單。</span><Button variant="outline" onClick={()=>navigate('in')}>前往進貨管理</Button></div></TableCell></TableRow>}</TableBody></Table>}
 <div className="panel-footer"><span>每筆來料明細開立一張工單，承接本批客戶圖面</span><span>剩餘數量 = 訂單數量 − 累計良品</span></div></section>
 <p className="production-hint">來料 → 確認客戶圖面 → 派工 → 開工 → 產量回報 → 完工 → 出貨 → 請加工費</p>
 <Dialog open={!!active&&!modal} onOpenChange={v=>{if(!v)setActiveId(null)}}><DialogContent className="detail-dialog job-detail sm:max-w-4xl"><DialogTitle>生產工單 {active?.number}</DialogTitle><DialogDescription>{active?.customer} · {active?.receipt_number?'來料 '+active.receipt_number:'訂單 '+active?.order_number}</DialogDescription>{active&&<><div className="job-title"><div><h2>{active.product}</h2><p>{active.spec||'未填規格'}</p></div>{jobStatus(active)}</div>{active.material_snapshot&&active.drawing_snapshot&&<section className="machining-spec"><h3>本批加工要求 · {active.drawing_snapshot.number} / {active.drawing_snapshot.version}</h3><p>{active.material_snapshot.material} · {active.material_snapshot.drive} × {active.material_snapshot.size} × {active.material_snapshot.profile} · {active.material_snapshot.style}</p><DrawingDimensions drawing={active.drawing_snapshot} raw={active.material_snapshot}/>{active.drawing_snapshot.file_name&&<a className="drawing-link" href={'/api/drawing-file?id='+encodeURIComponent(active.drawing_snapshot.id)} target="_blank" rel="noreferrer">開啟圖檔：{active.drawing_snapshot.file_name} ↗</a>}<small>上列為本批選定圖面的目標尺寸，實際尺寸請依量測確認。</small></section>}<div className="job-facts"><div><small>目標數量</small><b>{fmt(active.quantity)} {active.unit}</b></div><div><small>交貨期限</small><b>{active.due}</b></div><div><small>機台</small><b>{active.machine||'尚未指定'}</b></div><div><small>操作人員</small><b>{active.operator||'尚未指定'}</b></div></div><div className="job-production"><div><span>累計良品</span><b>{fmt(active.good)}</b></div><div><span>累計不良</span><b>{fmt(active.defective)}</b></div><div><span>還需良品</span><b>{fmt(active.quantity-active.good)}</b></div><div><span>已出貨</span><b>{fmt(active.shipped)}</b></div></div><Progress value={active.good/active.quantity*100} aria-label="生產完成比例"/><small>不良品不計入完成數；剩餘數量為需要補足的良品。</small>
 <div className="job-actions print-button">{['pending','paused'].includes(active.status)&&<><Button disabled={busy} variant="outline" onClick={()=>open('assign',{id:active.id,machine:active.machine,operator:active.operator})}><UserRound size={16}/>{active.machine?'重新派工':'指定機台 / 人員'}</Button><Button disabled={busy||!active.machine||!active.operator} onClick={()=>state(active,'running')}><Play size={16}/>{active.status==='paused'?'繼續加工':'開工'}</Button></>}{active.status==='running'&&<><Button disabled={busy} onClick={()=>open('report',{id:active.id})}><Plus size={16}/>回報產量</Button><Button disabled={busy} variant="outline" onClick={()=>state(active,'paused')}><Pause size={16}/>暫停</Button></>}{['running','paused'].includes(active.status)&&<Button disabled={busy||active.good!==active.quantity} variant="outline" onClick={()=>state(active,'completed')}><CheckCheck size={16}/>確認完工</Button>}{active.status==='completed'&&active.shipped<active.good&&<Button onClick={()=>open('ship',{id:active.id,quantity:active.good-active.shipped})}><Truck size={16}/>轉出貨單</Button>}<Button variant="outline" onClick={()=>setLabelJob(active)}><Printer size={16}/>派工標籤</Button><Button variant="ghost" onClick={()=>window.print()}><Printer size={16}/>列印工單</Button></div>
 {active.status==='pending'&&(!active.machine||!active.operator)&&<p className="production-hint">請先指定機台與操作人員，再按「開工」。</p>}{active.status==='completed'&&<p className="production-hint">尚可出貨 {fmt(active.good-active.shipped)} {active.unit}。出貨後至「出貨管理」勾選單據請款。</p>}
 {active.order_note&&<p className="job-note">訂單備註：{active.order_note}</p>}<div className="job-times"><span>首次開工：{timestamp(active.started_at)}</span><span>完工：{timestamp(active.completed_at)}</span></div><h3 className="job-report-title">產量回報紀錄</h3><Table><TableHeader><TableRow>{['回報時間','人員','本次良品','本次不良','備註'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{current.reports.filter(r=>r.work_order_id===active.id).map(r=><TableRow key={r.id}><TableCell>{timestamp(r.reported_at)}</TableCell><TableCell>{r.operator}</TableCell><TableCell>{fmt(r.good)}</TableCell><TableCell>{fmt(r.defective)}</TableCell><TableCell>{r.note||'—'}</TableCell></TableRow>)}{!current.reports.some(r=>r.work_order_id===active.id)&&<TableRow><TableCell colSpan={5}>尚無回報紀錄</TableCell></TableRow>}</TableBody></Table></>}</DialogContent></Dialog>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="form-dialog sm:max-w-2xl"><DialogTitle>{({order:'新增客戶訂單',work_order:'開立生產工單',assign:'指定機台與操作人員',report:'回報本次產量',ship:'工單轉出貨單'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>{modal==='report'?'填寫這一次新增的數量，系統會自動累加。':modal==='ship'?'依訂單單價建立出貨單，支援分批出貨。':modal==='work_order'?'依訂單產品與數量開立工單，可同時派工，或稍後再指定。':'必填欄位以 * 標示。'}</DialogDescription>{form&&<form onSubmit={submit}><div className="form-grid">{modal==='order'&&<><Field label="客戶 *"><Select value={form.partner_id} onValueChange={v=>change('partner_id',v)}><SelectTrigger aria-label="選擇訂單客戶" className="w-full"><SelectValue placeholder="選擇客戶"/></SelectTrigger><SelectContent>{partners.filter(p=>p.kind==='customer').map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select>{!partners.some(p=>p.kind==='customer')&&<Button type="button" variant="link" onClick={()=>navigate('partner')}>請先至往來廠商新增客戶</Button>}</Field><Field label="品名 *"><Input required maxLength={200} value={form.product} onChange={e=>change('product',e.target.value)} placeholder="例如：1/2 六角套筒"/></Field><Field label="訂單日期 *"><Input type="date" required value={form.date} onChange={e=>change('date',e.target.value)}/></Field><Field label="交期 *"><Input type="date" required min={form.date} value={form.due} onChange={e=>change('due',e.target.value)}/></Field><Field label="規格 / 圖號"><Input value={form.spec} onChange={e=>change('spec',e.target.value)} placeholder="例如：17 mm・50BV30・圖號 A01"/></Field><Field label="訂單數量 *"><Input required type="number" min={1} max={10000000} step={1} value={form.quantity} onChange={e=>change('quantity',Number(e.target.value))}/></Field><Field label="單位 *"><Input required value={form.unit} onChange={e=>change('unit',e.target.value)}/></Field><Field label="未稅單價（元） *"><Input required type="number" min={0} max={10000000} step="0.01" value={form.price} onChange={e=>change('price',Number(e.target.value))}/></Field></>}
 {['work_order','assign'].includes(modal)&&<><Field label={'機台'+(modal==='assign'?' *':'')}><Input required={modal==='assign'} maxLength={200} value={form.machine} onChange={e=>change('machine',e.target.value)} placeholder="例如：車床 02"/></Field><Field label={'操作人員'+(modal==='assign'?' *':'')}><Input required={modal==='assign'} maxLength={200} value={form.operator} onChange={e=>change('operator',e.target.value)} placeholder="姓名或員工編號"/></Field></>}
 {modal==='report'&&<><Field label="本次良品數 *"><Input required type="number" min={0} step={1} max={selectedJob?selectedJob.quantity-selectedJob.good:10000000} value={form.good} onChange={e=>change('good',Number(e.target.value))}/><small>還需 {fmt(selectedJob?selectedJob.quantity-selectedJob.good:0)} 件良品</small></Field><Field label="本次不良數 *"><Input required type="number" min={0} max={10000000} step={1} value={form.defective} onChange={e=>change('defective',Number(e.target.value))}/></Field></>}
 {modal==='ship'&&<><Field label="包裝數量 *"><Input required type="number" min={0} step={1} value={form.packages} onChange={e=>change('packages',Number(e.target.value))}/></Field><Field label="包裝單位"><Select value={form.package_unit} onValueChange={v=>change('package_unit',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="包">包</SelectItem><SelectItem value="桶">桶</SelectItem></SelectContent></Select></Field><Field label="實際送出鐵桶數（含空桶） *"><Input required type="number" min={0} step={1} value={form.barrels} onChange={e=>change('barrels',Number(e.target.value))}/></Field><Field label="出貨日期 *"><Input type="date" required value={form.date} onChange={e=>change('date',e.target.value)}/></Field><Field label="本次出貨數量 *"><Input required type="number" min={1} max={selectedJob?selectedJob.good-selectedJob.shipped:0} step={1} value={form.quantity} onChange={e=>change('quantity',Number(e.target.value))}/><small>尚可出貨 {fmt(selectedJob?selectedJob.good-selectedJob.shipped:0)} {selectedJob?.unit}</small></Field><Field label="稅率（%） *"><Input required type="number" min={0} max={100} step="0.01" value={form.tax_rate} onChange={e=>change('tax_rate',Number(e.target.value))}/></Field><div className="ship-total"><small>含稅合計</small><b>NT$ {amount((()=>{const n=form.quantity*(selectedJob?.price||0);return n+Math.round(n*form.tax_rate/100)})())}</b></div></>}
 </div>{['order','report','ship'].includes(modal)&&<Field label={modal==='report'?'備註 / 不良原因':'備註'}><Input maxLength={2000} value={form.note} onChange={e=>change('note',e.target.value)}/></Field>}{modal==='work_order'&&<p className="production-hint">{current.orders.find(o=>o.id===form.order_id)?.product} · {fmt(current.orders.find(o=>o.id===form.order_id)?.quantity||0)} {current.orders.find(o=>o.id===form.order_id)?.unit}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal('')}>取消</Button><Button type="submit" disabled={busy||(modal==='order'&&!form.partner_id)}>{busy?'儲存中…':'確認儲存'}</Button></div></form>}</DialogContent></Dialog>
 </div>
}
