'use client';
import {drawingSummary,drawingReady} from './drawing-types';
import {useState,useRef,Fragment} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {receiptGroups,intakeStatus,matchesReceipt,initial} from './receipt-filter';
type Row=Record<string,any>;
const fmt=(n:number)=>new Intl.NumberFormat('zh-TW').format(n);
export default function ReceiptList({intakes,documents,loading,onDetail,onAction,onWork,showDocument}:{intakes:Row[];documents:Row[];loading:boolean;onDetail:(i:Row)=>void;onAction:(i:Row)=>void;onWork:()=>void;showDocument:(d:Row)=>void}){
 const [f,setF]=useState(initial),[more,setMore]=useState(false),[expanded,setExpanded]=useState<string[]>([]),[selected,setSelected]=useState(''),[page,setPage]=useState(1),[mode,setMode]=useState('documents');
 const scroll=useRef(0),root=useRef<HTMLDivElement>(null);
 const groups=receiptGroups(intakes),matches=groups.filter(g=>matchesReceipt(g,f)),count=Math.max(1,Math.ceil(matches.length/25)),current=Math.min(page,count),visible=matches.slice((current-1)*25,current*25),active=groups.find(g=>g.id===selected);
 const change=(k:keyof typeof initial,v:any)=>{setF(s=>({...s,[k]:v}));setPage(1)};
 const enter=(id:string)=>{scroll.current=window.scrollY;setSelected(id);requestAnimationFrame(()=>root.current?.scrollIntoView({block:'start'}))};
 const back=()=>{setSelected('');requestAnimationFrame(()=>window.scrollTo({top:scroll.current,behavior:'instant'}))};
 const options=(key:string,label:string)=>Array.from(new Map(intakes.map(i=>[i[key],i[label]])).entries()).filter(([id])=>id).map(([value,label])=>({value,label}));
 const choose=(key:'supplier'|'status',label:string,items:{value:string;label:string}[])=><label className="field"><span>{label}</span><Select value={f[key]||'all'} onValueChange={v=>change(key,v==='all'?'':v)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部</SelectItem>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label>;
 const status=(lines:Row[])=>['待圖面','部分分配','待派工','部分派工','已全部派工','加工完成'].map(s=>{const n=lines.filter(i=>intakeStatus(i)===s).length;return n?<span key={s} className={'status '+(s==='加工完成'?'done':'wait')}>{n} 筆{s}</span>:null});
 const totals=(g:typeof groups[number])=>{const doc=documents.find(d=>d.id===g.id);return <>{g.lines.length} 筆 · {fmt(g.lines.reduce((n,i)=>n+i.quantity,0))} 支<small>包數 {fmt(g.lines.reduce((n,i)=>n+(i.package_unit==='包'?i.packages:0),0))} 包 · 實收鐵桶 {doc?fmt(doc.barrels??0):'—'} 桶</small></>};
 const linesTable=(lines:Row[])=><Table><TableHeader><TableRow>{['項次／來料規格','數量／件數','加工圖面／目標尺寸','狀態','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{lines.map((i,index)=><TableRow key={i.id}><TableCell><b>{index+1}. {i.material_snapshot.drive} × {i.material_snapshot.size} × {i.material_snapshot.profile}</b><small>{i.material_snapshot.name} · {i.material_snapshot.material} · {i.material_snapshot.style}</small><small>來料 Ø{i.material_snapshot.raw_diameter} × {i.material_snapshot.raw_length}L</small></TableCell><TableCell>{fmt(i.quantity)} 支<small>{fmt(i.packages)} {i.package_unit||'件'}</small><small>已分配 {i.allocations?.length?i.allocations.reduce((n:number,a:Row)=>n+a.quantity,0):i.dispatched?i.quantity:0} 支</small><small>未分配 {i.allocations?.length?i.quantity-i.allocations.reduce((n:number,a:Row)=>n+a.quantity,0):i.dispatched?0:i.quantity} 支</small></TableCell><TableCell>{i.allocations?.length?<span>{i.allocations.length} 種加工分配（點開查看）</span>:i.drawing_snapshot?<><b>{i.drawing_snapshot.number} / {i.drawing_snapshot.version}</b><small>{drawingSummary(i.drawing_snapshot)}</small></>:'待確認圖面'}</TableCell><TableCell>{intakeStatus(i)}</TableCell><TableCell><div className="receipt-list-actions"><Button variant="ghost" onClick={()=>onDetail(i)}>明細／加工條件</Button><Button variant="outline" onClick={()=>onAction(i)}>加工分配／修改</Button>{!!i.dispatched&&<Button variant="ghost" onClick={onWork}>看工單</Button>}</div></TableCell></TableRow>)}</TableBody></Table>;
 return <div ref={root} className="receipt-list">
 {selected?<><div className="receipt-page-head"><Button variant="outline" onClick={back}>← 返回進貨單總覽</Button><b>單張進貨單</b></div>{active?<><div className="receipt-document-summary"><h2>{active.head.receipt_number}</h2><p>{active.head.date} · 客戶：{active.head.customer} · 前關廠商：{active.head.supplier}</p><div>{totals(active)}</div><div className="receipt-statuses">{status(active.lines)}</div>{active.head.note&&<p>備註：{active.head.note}</p>}<Button variant="outline" disabled={!documents.some(d=>d.id===active.id)} onClick={()=>{const doc=documents.find(d=>d.id===active.id);if(doc)showDocument(doc)}}>查看原單／列印／鐵桶紀錄</Button></div>{linesTable(active.lines)}</>:<p className="empty-state">{loading?'正在讀取單據…':'此單已不在目前來料清單，可能已作廢。'}</p>}</>:<>
 <div className="receipt-list-filters"><div className="receipt-filter-primary"><details className="receipt-customer-select"><summary>客戶：{f.customers.length?`已選 ${f.customers.length} 家`:'全部客戶'}</summary><div><Button variant="ghost" onClick={()=>change('customers',[])}>全部客戶</Button>{options('customer_id','customer').map(x=><label key={x.value}><Checkbox checked={f.customers.includes(x.value)} onCheckedChange={v=>change('customers',v?[...f.customers,x.value]:f.customers.filter(id=>id!==x.value))}/>{x.label}</label>)}</div></details><label className="field"><span>進貨日期起</span><Input type="date" value={f.from} onChange={e=>change('from',e.target.value)}/></label><label className="field"><span>進貨日期迄</span><Input type="date" value={f.to} onChange={e=>change('to',e.target.value)}/></label><label className="field"><span>單號</span><Input placeholder="輸入部分單號" value={f.number} onChange={e=>change('number',e.target.value)}/></label></div>
 <div className="receipt-list-actions"><Button variant="outline" onClick={()=>{const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());setF(s=>({...s,from:date,to:date}));setPage(1)}}>今天</Button><Button variant="outline" onClick={()=>{const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const [y,m]=date.split('-').map(Number);const end=new Date(Date.UTC(y,m,0)).getUTCDate();setF(s=>({...s,from:date.slice(0,7)+'-01',to:date.slice(0,7)+'-'+end}));setPage(1)}}>本月</Button><Button variant="outline" aria-expanded={more} onClick={()=>setMore(!more)}>更多條件{[f.supplier,f.status,f.spec].filter(Boolean).length?`（${[f.supplier,f.status,f.spec].filter(Boolean).length}）`:''}</Button><Button variant="ghost" onClick={()=>{setF(initial);setPage(1)}}>清除全部條件</Button></div>
 {more&&<div className="receipt-filter-primary">{choose('supplier','前關廠商',options('supplier_id','supplier'))}{choose('status','作業狀態',['待圖面','部分分配','待派工','部分派工','已全部派工','加工完成'].map(value=>({value,label:value})))}<label className="field"><span>料的規格／圖號</span><Input placeholder="例如 0410、04S10、M10" value={f.spec} onChange={e=>change('spec',e.target.value)}/></label></div>}
 {f.from&&f.to&&f.from>f.to&&<p role="alert" className="error">起日不可晚於迄日。</p>}
 {f.customers.length>0&&<p>已選客戶：{options('customer_id','customer').filter(x=>f.customers.includes(x.value)).map(x=>x.label).join('、')}</p>}
 <div className="receipt-list-actions"><strong aria-live="polite">符合 {matches.length} 張／全部 {groups.length} 張</strong><Button variant={mode==='documents'?'default':'outline'} onClick={()=>setMode('documents')}>依單號查看</Button><Button variant={mode==='lines'?'default':'outline'} onClick={()=>setMode('lines')}>全部明細查看</Button></div><p className="material-caption">規格與狀態須在同一筆明細符合；找到後顯示整張單。每頁最多 25 張。</p></div>
 {loading&&<p role="status">正在更新單據…</p>}
 <Table><TableHeader><TableRow>{['單號／進貨日期','客戶／前關廠商','明細／數量／包桶','作業狀態','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(g=><Fragment key={g.id}><TableRow className="receipt-group-head"><TableCell><Button variant="link" onClick={()=>enter(g.id)}>{g.head.receipt_number}</Button><small>{g.head.date}</small></TableCell><TableCell><b>{g.head.customer}</b><small>前關：{g.head.supplier}</small></TableCell><TableCell>{totals(g)}</TableCell><TableCell><div className="receipt-statuses">{status(g.lines)}</div></TableCell><TableCell><div className="receipt-list-actions"><Button variant="outline" aria-expanded={mode==='lines'||expanded.includes(g.id)} onClick={()=>{if(mode==='lines'){setMode('documents');setExpanded([])}else setExpanded(s=>s.includes(g.id)?s.filter(x=>x!==g.id):[...s,g.id])}}>{mode==='lines'||expanded.includes(g.id)?'收起明細':'展開明細'}</Button><Button onClick={()=>enter(g.id)}>開啟單據</Button></div></TableCell></TableRow>{(mode==='lines'||expanded.includes(g.id))&&<TableRow><TableCell colSpan={5} className="receipt-nested">{linesTable(g.lines)}</TableCell></TableRow>}</Fragment>)}</TableBody></Table>
 {!matches.length&&!loading&&<div className="empty-state">{groups.length?'沒有符合條件的進貨單，請調整篩選。':'尚無進貨單，請按「登記來料」。'}</div>}
 <nav className="catalog-pagination" aria-label="進貨單分頁"><span>第 {current}／{count} 頁</span><div><Button variant="outline" disabled={current===1} onClick={()=>setPage(current-1)}>上一頁</Button><Button variant="outline" disabled={current===count} onClick={()=>setPage(current+1)}>下一頁</Button></div></nav></>}
 </div>
}
