'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {verifyBackup} from './backup-format';
import {toast} from 'sonner';
type Row=Record<string,any>;
const names:Record<string,string>={partners:'往來廠商',documents:'進出貨單',invoices:'請款單',payments:'收款',sales_orders:'訂單',work_orders:'工單',production_reports:'報工',material_specs:'來料規格',drawings:'加工圖面',drawing_specs:'圖面適用料',intakes:'進貨明細',intake_allocations:'加工分配',barrel_entries:'鐵桶帳',series_drawings:'系列圖面',series_drawing_rows:'系列圖面尺寸列'};
const when=(s:string)=>new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});
export default function SafetyCenter(){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<Row|null>(null),[data,setData]=useState<{audit:Row[];trash:Row[]}>({audit:[],trash:[]}),[error,setError]=useState(''),[restore,setRestore]=useState<Row|null>(null),[reason,setReason]=useState('');
 async function load(before?:number){try{const r=await fetch('/api/safety'+(before?'?before='+before:''),{cache:'no-store'}),b=await r.json() as Row;if(!r.ok)throw Error(b.error);setData(d=>({audit:before?[...d.audit,...b.audit]:b.audit,trash:b.trash}));setError('')}catch(e){setError(String(e))}}
 useEffect(()=>{load()},[]);
 async function backup(){setBusy(true);setResult(null);try{const r=await fetch('/api/backup',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error((b as Row).error);const checked=await verifyBackup(b);const blob=new Blob([JSON.stringify(b)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='factory-flow-'+new Date().toISOString().replaceAll(':','-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setResult({...checked,download:true});toast.success('備份檢查通過，已送交瀏覽器下載；請確認檔案已存到電腦')}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 const [local,setLocal]=useState<Row|null>(null);
 async function localBackup(){setBusy(true);try{const r=await fetch('/api/local-backup',{method:'POST'}),b=await r.json() as Row;if(!r.ok)throw Error(b.error);setLocal(b);toast.success('已備份到 '+b.target)}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 async function inspect(file?:File){if(!file)return;setBusy(true);setResult(null);try{if(file.size>40*1024*1024)throw Error('本版檢查上限為 40 MB');setResult(await verifyBackup(JSON.parse(await file.text())))}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 async function recover(){if(!restore)return;setBusy(true);try{const r=await fetch('/api/safety',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audit_id:restore.id,reason})}),b=await r.json() as Row;if(!r.ok)throw Error(b.error);setRestore(null);await load();toast.success('加工分配已復原，保留原圖面與數量')}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 return <div className="material-space"><section className="panel safety-panel"><h2>備份與復原</h2><p>完整備份包含單據、規格、加工圖面、加工分配、草稿、操作紀錄與所有被引用的圖檔。請先暫停同事輸入並儲存草稿，再匯出。</p><div className="editor-actions"><Button disabled={busy} onClick={localBackup}>{busy?'處理中…':'一鍵備份到資料夾'}</Button><Button variant="outline" disabled={busy} onClick={backup}>{busy?'處理中…':'匯出完整備份（含圖檔）'}</Button><label className="field"><span>選擇備份檔，檢查完整性</span><Input disabled={busy} type="file" accept=".json,application/json" onChange={e=>inspect(e.target.files?.[0])}/></label></div>{local&&<p role="status">一鍵備份完成：{String(local.target)}（附件 {String(local.files)} 個）。請確認該資料夾在外接硬碟或 NAS 上。</p>}<p>「一鍵備份到資料夾」會把整個資料庫與圖檔複製到 .env 設定的備份路徑，建議每天下班按一次。本版資料表內容上限約 4 MB，含附件單檔備份上限 16 MB；超過或附件遺失時會中止，不會把不完整檔案標為成功。這是手動備份，尚未設定自動備份。</p>{result&&<div role="status" className="allocation-detail-section"><b>檔案完整性與資料關聯檢查通過</b><p>{when(result.created_at)} · {result.version} · {result.rows} 筆資料 · {result.files} 個附件</p><p>{result.download?'請確認瀏覽器下載成功，並另存一份到其他儲存位置。':'此次檢查只讀取檔案，不會匯入或覆蓋正式資料。'}</p><details><summary>查看資料表筆數</summary>{result.tables.map((t:Row)=><p key={t.name}>{names[t.name]||t.name}：{t.count} 筆</p>)}</details></div>}<details><summary>如何用備份副本做還原演練？</summary><p>下載演練工具，在具備 Node.js 22.13 以上版本的電腦執行。工具會把備份還原到新的 SQLite 檔案與附件資料夾，核對資料內容、關聯及圖檔；不連接正式系統。可將備份交給我們協助演練。</p><a href="/backup-restore.mjs" download>下載還原演練工具</a><pre>node backup-restore.mjs 備份檔.json 新的輸出資料夾</pre><p>網頁上的完整性檢查不等於已完成你的實際資料還原演練；請保存演練產生的 report.json。</p></details></section>
 <section className="panel safety-panel"><h2>移除紀錄／可復原項目</h2><p>此處保留 V20 起移除的未派工加工分配（最近 100 筆）。復原前會核對剩餘數量、單據及圖面狀態。正式單據、客戶、料、圖面及工單禁止直接永久刪除；單據作廢與圖面停用保留原紀錄。</p>{!data.trash.length&&<p>目前沒有可復原的加工分配。</p>}{data.trash.map(a=>{const x=JSON.parse(a.before),dr=JSON.parse(x.drawing_snapshot);return <div className="allocation-detail-section" key={a.id}><b>{dr.number}／{dr.version} · {x.quantity} 支</b><p>移除於 {when(a.stamp)}</p><Button onClick={()=>{setRestore(a);setReason('')}}>復原這筆加工分配</Button></div>})}</section>
 <section className="panel safety-panel"><h2>操作紀錄</h2><p>V20 起記錄主要營運資料的新增、修改與移除，包含前後內容；草稿編輯不列入此清單，但已暫存草稿會納入備份。既有專用修改紀錄也保留。</p>{error&&<p role="alert">{error}</p>}<Button variant="outline" onClick={()=>load()}>重新整理紀錄</Button>{data.audit.map(a=><details className="allocation-detail-section" key={a.id}><summary>{when(a.stamp)} · {names[a.table_name]||a.table_name} · {({insert:'新增',update:'修改',delete:'移除',restore:'復原'} as Row)[a.action]||a.action}</summary><p>人員：{(()=>{try{const p=JSON.parse(a.actor);return p.email||(p.id==='unavailable'?'未取得登入身分（系統或非網頁操作）':p.id)}catch{return a.actor}})()}</p><p>紀錄識別：{a.record_id}</p><div className="audit-values"><div><b>修改前</b><pre>{a.before?JSON.stringify(JSON.parse(a.before),null,2):'—'}</pre></div><div><b>修改後</b><pre>{a.after?JSON.stringify(JSON.parse(a.after),null,2):'—'}</pre></div></div></details>)}{data.audit.length>=100&&<Button variant="outline" onClick={()=>load(data.audit.at(-1)?.sequence)}>載入更早紀錄</Button>}</section>
 <Dialog open={!!restore} onOpenChange={v=>{if(!v&&!busy)setRestore(null)}}><DialogContent><DialogTitle>復原加工分配</DialogTitle><DialogDescription>使用移除前的圖面快照、數量、單價與交期，重新列入該筆進貨的已分配數量。</DialogDescription><Input aria-label="復原原因" placeholder="請填復原原因" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy||!reason.trim()} onClick={recover}>確認復原</Button></DialogContent></Dialog></div>
}
