import {uncutLength} from './uncut-length';
import {useId} from 'react';
import {grooveError} from './groove-types';
type Row=Record<string,any>;
export default function SocketDiagram({drawing:d,raw}:{drawing?:Row|null;raw?:Row}){
 const id=useId().replaceAll(':',''),L=Number(d?.length),D=Number(raw?.raw_diameter),valid=Number.isFinite(L)&&Number.isFinite(D)&&L>0&&D>0&&d?.format==='ends-v1';
 const start=100,end=500,cy=132,scale=400/(L||1),rad=42,drive=d?.ends?.drive,work=d?.ends?.work,g=d?.groove;
 const radius=(x:number)=>{let dia=D;for(const [e,distance] of [[drive,x],[work,L-x]] as const)if(e?.mode==='machine'&&Number(e.diameter)>0&&Number(e.cut_length)>distance)dia=Math.min(dia,Number(e.diameter));return rad*(dia/(D||1))};
 const cuts=valid?[0,L,...(drive?.mode==='machine'?[Math.min(L,Number(drive.cut_length)||0)]:[]),...(work?.mode==='machine'?[Math.max(0,L-(Number(work.cut_length)||0))]:[])].sort((a,b)=>a-b):[0,1];
 const points:string[]=[];for(let i=0;i<cuts.length-1;i++){const a=cuts[i],b=cuts[i+1],r=radius((a+b)/2);points.push(`${start+a*scale},${cy-r}`,`${start+b*scale},${cy-r}`)}for(let i=cuts.length-2;i>=0;i--){const a=cuts[i],b=cuts[i+1],r=radius((a+b)/2);points.push(`${start+b*scale},${cy+r}`,`${start+a*scale},${cy+r}`)}
 const grooveValid=valid&&g?.kind==='round'&&!grooveError(g,String(L),String(D));const center=grooveValid?(g.base==='drive'?1:-1)*(Number(g.position)+(g.reference==='edge'?Number(g.width)/2:0))+(g.base==='work'?L:0):0;const gx=start+center*scale,gw=Math.max(6,Number(g?.width)*scale||0),gr=radius(center);
 const retained=uncutLength(d,'drive'),retainedEnd=retained===null?null:start+retained*scale;
 const caption=(e:Row|undefined)=>!e||e.mode==='pending'?'加工尺寸待確認':e.mode==='unchanged'?'外徑不加工':`Ø${e.diameter||'待填'} × ${e.cut_length||'待填'}L`;
 return <svg className="socket-diagram" viewBox="0 0 600 320" role="img" aria-label="套筒加工位置示意圖，左方孔端、右工作端，尺寸以標示為準"><defs><marker id={id} viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="black"/></marker></defs><g fill="black" fontSize="24" textAnchor="middle"><text x="145" y="24">方孔端 {raw?.drive||''}</text><text x="455" y="24">工作端 {raw?.size||''}</text><text x="145" y="49">{caption(drive)}</text><text x="455" y="49">{caption(work)}</text></g><g stroke="black" strokeWidth="2" fill="white">{valid?<polygon points={points.join(' ')}/>:<rect x="100" y="90" width="400" height="84"/>}<ellipse cx="100" cy={cy} rx="19" ry={valid?radius(0.00001):rad} fill="white"/><g transform={`translate(100 132) scale(1 ${(valid?radius(0.00001):rad)/rad}) translate(-100 -132)`}><path d="M90 111 L110 115 L110 153 L90 157 Z" fill="white" strokeWidth="2.5"/><path d="M96 113 V151 L110 148" fill="none" strokeWidth="1"/></g><path d="M122 132H520" strokeDasharray="9 5" strokeWidth="1"/>{grooveValid&&<>{[-1,1].map(sign=><g key={sign}><path d={`M${gx-gw/2} ${cy+sign*gr}H${gx+gw/2}`} stroke="white" strokeWidth="4"/><path d={`M${gx-gw/2} ${cy+sign*gr} Q${gx} ${cy+sign*Math.max(4,gr-18)} ${gx+gw/2} ${cy+sign*gr}`} fill="none" strokeWidth="3"/></g>)}<path d={`M${gx} ${cy+gr+4}V191`} fill="none"/></>}<path d="M100 180V280 M500 180V280"/>{valid&&retainedEnd!==null&&retained!>0&&<><path d={`M${retainedEnd} 180V225`} strokeDasharray="4 3"/><path d={`M104 218H${retainedEnd-4}`} markerStart={`url(#${id})`} markerEnd={`url(#${id})`}/></>}<path d="M104 273H496" markerStart={`url(#${id})`} markerEnd={`url(#${id})`}/></g><g textAnchor="middle" fill="black">{valid&&retained!==null&&<text x="300" y="249" fontSize="24">未加工長度 {retained} mm（方孔端）</text>}<text x="300" y="298" fontSize="24">完成總長 {d?.length||'待確認'} mm</text><text x="300" y="77" fontSize="15">{g?.kind==='round'?'圓一溝（位置依標示）':g?.kind==='none'?'無溝':g?.kind==='custom'?`${g.name}：輪廓依附件`:'溝槽型式待確認'}</text><text x="300" y="317" fontSize="12">示意圖，非等比例；未確認尺寸不得據此加工</text></g></svg>
}
