import {stampTaipei} from '@/lib/dates';
import {manageDrawing} from './drawing-management';
import {drawingInput,validateDrawingRaw} from './drawing-validation';
import {drawingSummary,drawingReady,drawingMatches} from '@/app/drawing-types';
import {allocationAction} from './allocations';
import {nextReceiptNumber,barrelStatements} from '../barrels-helper';
import { saveMaterials,materialInput,draftInput } from './batch';
import { database } from '@/db/raw';
import { storage } from '@/storage';
import { z } from 'zod';
import { defaults, fields, specLabel, materialCode } from '@/app/material-types';
const text=z.string().trim().min(1).max(200);
const decimal=z.string().trim().regex(/^\d+(\.\d+)?$/).refine(x=>Number(x)>0&&Number(x)<=10000);
const material=z.object({material:text,name:text,drive:text,size:text,profile:text,raw_length:decimal,raw_diameter:decimal,style:text});
const target=drawingInput;
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
const bucket=()=>storage;
export async function GET(){try{const db=database();const [o,s,d,r,draft,allocations,audit,links,drawingAudit]=await db.batch([
 db.prepare('SELECT * FROM spec_options ORDER BY field,value'),db.prepare('SELECT * FROM material_specs ORDER BY rowid DESC'),
 db.prepare('SELECT d.*,p.name AS customer, (d.used=1 OR EXISTS(SELECT 1 FROM intakes i WHERE i.drawing_id=d.id) OR EXISTS(SELECT 1 FROM intake_allocations a WHERE a.drawing_id=d.id)) AS in_use FROM drawings d JOIN partners p ON p.id=d.customer_id ORDER BY d.rowid DESC'),
 db.prepare(`SELECT i.*,d.number AS receipt_number,d.date,d.partner_id AS supplier_id,d.note,p.name AS customer,v.name AS supplier,w.id AS work_order_id,w.number AS work_number,w.status AS work_status FROM intakes i JOIN documents d ON d.id=i.document_id JOIN partners p ON p.id=i.customer_id JOIN partners v ON v.id=d.partner_id LEFT JOIN work_orders w ON w.intake_id=i.id AND w.allocation_id IS NULL WHERE d.voided=0 ORDER BY d.rowid DESC,i.position ASC,i.rowid ASC`),db.prepare("SELECT data,updated_at FROM material_drafts WHERE id='current'"),db.prepare("SELECT a.*,w.id AS work_order_id,w.number AS work_number,w.status AS work_status FROM intake_allocations a LEFT JOIN work_orders w ON w.allocation_id=a.id ORDER BY a.rowid"),db.prepare("SELECT * FROM intake_audit ORDER BY rowid DESC"),db.prepare("SELECT * FROM drawing_specs"),db.prepare("SELECT * FROM drawing_audit ORDER BY rowid DESC")
]);const savedDraft=draft.results[0] as {data:string;updated_at:string}|undefined;return Response.json({draft:savedDraft?{data:JSON.parse(savedDraft.data),updated_at:savedDraft.updated_at}:null,options:o.results,specs:s.results.map((x:any)=>({...x,legacy_code:x.code,code:materialCode(JSON.parse(x.data)),data:JSON.parse(x.data)})),drawings:d.results.map((x:any)=>({...x,audit:drawingAudit.results.filter((a:any)=>a.drawing_id===x.id),spec_ids:[x.spec_id,...links.results.filter((l:any)=>l.drawing_id===x.id).map((l:any)=>l.spec_id)],preferred_spec_ids:[...(x.preferred?[x.spec_id]:[]),...links.results.filter((l:any)=>l.drawing_id===x.id&&l.preferred).map((l:any)=>l.spec_id)],data:JSON.parse(x.data)})),intakes:r.results.map((x:any)=>({...x,allocations:allocations.results.filter((a:any)=>a.intake_id===x.id).map((a:any)=>({...a,drawing_snapshot:JSON.parse(a.drawing_snapshot)})),audit:audit.results.filter((a:any)=>a.intake_id===x.id),material_snapshot:JSON.parse(x.material_snapshot),drawing_snapshot:x.drawing_snapshot?JSON.parse(x.drawing_snapshot):null}))},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'來料資料暫時無法讀取，請重試。'},{status:503})}}
export async function POST(req:Request){let uploaded:string|null=null;try{
 if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'請從本站操作'},{status:403});
 let file:File|null=null;let payload:unknown;
 if(req.headers.get('content-type')?.includes('multipart/form-data')){const f=await req.formData();payload=JSON.parse(String(f.get('payload')));const entry=f.get('file');if(entry instanceof File&&entry.size)file=entry;}else payload=await req.json();
 const b=z.object({action:text,request_id:z.string().uuid()}).passthrough().parse(payload);const db=database(req);const id=b.request_id;
 const stamp=new Date().toISOString();const no=(p:string)=>`${p}-${stampTaipei()}-${id.slice(0,8).toUpperCase()}`;
 const managed=await manageDrawing(b,req);if(managed)return Response.json(managed);
 const allocated=await allocationAction(b,req);if(allocated)return Response.json(allocated);
 if(b.action==='defaults'){await db.batch(Object.entries(defaults).flatMap(([field,values])=>values.map(value=>db.prepare('INSERT OR IGNORE INTO spec_options (id,field,value) VALUES (?,?,?)').bind(`${field}:${value}`,field,value))));}
 else if(b.action==='option'){const p=z.object({field:z.enum(['material','name','drive','size','profile','raw_length','raw_diameter','style']),value:text}).parse(b);if(p.field==='raw_length'||p.field==='raw_diameter')decimal.parse(p.value);await db.prepare('INSERT OR IGNORE INTO spec_options (id,field,value) VALUES (?,?,?)').bind(`${p.field}:${p.value}`,p.field,p.value).run();}
 else if(b.action==='draft'){const p=draftInput.parse(b.data);await db.prepare("INSERT INTO material_drafts (id,data,updated_at) VALUES ('current',?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(JSON.stringify(p),stamp).run();}
 else if(b.action==='batch_specs'){const p=z.object({rows:z.array(materialInput).min(1).max(100)}).parse(b);const remaining=b.remaining_draft===undefined?undefined:draftInput.parse(b.remaining_draft);const result=await saveMaterials(p.rows.map(data=>({data})),req);if(remaining)await db.prepare("INSERT INTO material_drafts (id,data,updated_at) VALUES ('current',?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(JSON.stringify(remaining),stamp).run();return Response.json({ok:true,...result});}
 else if(b.action==='spec'){const p=z.object({code:z.string().optional(),data:materialInput}).parse(b);const result=await saveMaterials([p],req);return Response.json({ok:true,id:result.ids[0],...result});}
 else if(b.action==='drawing'){const p=z.object({customer_id:text,spec_id:text,spec_ids:z.array(text).max(100).optional(),number:text,version:text,data:target,preferred:z.boolean()}).parse(b);
 if(await db.prepare('SELECT id FROM drawings WHERE id=?').bind(id).first())return Response.json({ok:true,id});
 const spec=await db.prepare('SELECT data FROM material_specs WHERE id=?').bind(p.spec_id).first<{data:string}>();if(!spec||!await db.prepare("SELECT id FROM partners WHERE id=? AND kind='customer'").bind(p.customer_id).first())throw Error('請選擇有效的客戶與來料規格');
 const raw=JSON.parse(spec.data);validateDrawingRaw(p.data,raw);const shared=[...new Set([p.spec_id,...(p.spec_ids||[])])];const sharedSpecs=(await db.prepare('SELECT id,data FROM material_specs WHERE id IN (SELECT value FROM json_each(?))').bind(JSON.stringify(shared)).all()).results as {id:string;data:string}[];if(sharedSpecs.length!==shared.length)throw Error('適用來料不存在');for(const extra of sharedSpecs)validateDrawingRaw(p.data,JSON.parse(extra.data));
 if(await db.prepare('SELECT id FROM drawings WHERE customer_id=? AND number=? AND version=? AND spec_id=?').bind(p.customer_id,p.number,p.version,p.spec_id).first())throw Error('此客戶、來料、圖號與版本已存在；修改圖面請另存新版本');
 if(file){if(file.size>5*1024*1024||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))throw Error('圖檔限 PDF、JPG、PNG、WebP，最大 5 MB');uploaded=`drawings/${id}/${crypto.randomUUID()}`;await bucket().put(uploaded,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}})}
 const stmts=[];if(p.preferred){stmts.push(db.prepare('UPDATE drawings SET preferred=0 WHERE customer_id=? AND spec_id IN (SELECT value FROM json_each(?))').bind(p.customer_id,JSON.stringify(shared)),db.prepare('UPDATE drawing_specs SET preferred=0 WHERE drawing_id IN (SELECT id FROM drawings WHERE customer_id=?) AND spec_id IN (SELECT value FROM json_each(?))').bind(p.customer_id,JSON.stringify(shared)))}stmts.push(db.prepare('INSERT INTO drawings (id,customer_id,spec_id,number,version,data,preferred,file_key,file_name,file_type) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,p.customer_id,p.spec_id,p.number,p.version,JSON.stringify(p.data),p.preferred?1:0,uploaded,file?.name||null,file?.type||null));stmts.push(db.prepare("INSERT INTO drawing_specs(id,drawing_id,spec_id,preferred) SELECT ?||':'||value,?,value,? FROM json_each(?)").bind(id,id,p.preferred?1:0,JSON.stringify(shared.filter(sid=>sid!==p.spec_id))));await db.batch(stmts);uploaded=null;
 }
 else if(b.action==='receipt'){
 const p=z.object({customer_id:text,supplier_id:text,date:day,number:z.string().trim().max(200).default(''),barrels:z.number().int().min(0).max(10000000).default(0),note:z.string().max(2000),lines:z.array(z.object({spec_id:text,drawing_id:z.string(),quantity:z.number().int().positive().max(10000000),packages:z.number().int().positive().max(10000000),package_unit:z.enum(['包','桶']).default('包'),due:day,fee:z.number().nonnegative().max(10000000)})).min(1).max(100)}).parse(b);
 if(await db.prepare('SELECT id FROM documents WHERE id=?').bind(id).first())return Response.json({ok:true,id});
 if(!await db.prepare("SELECT id FROM partners WHERE id=? AND kind='customer'").bind(p.customer_id).first()||!await db.prepare("SELECT id FROM partners WHERE id=? AND kind='supplier'").bind(p.supplier_id).first())throw Error('請分別選擇客戶與前關廠商');
 const specs=(await db.prepare('SELECT * FROM material_specs').all()).results as any[];const drawings=(await db.prepare('SELECT * FROM drawings WHERE disabled=0 AND customer_id=?').bind(p.customer_id).all()).results as any[];const links=(await db.prepare('SELECT * FROM drawing_specs').all()).results as any[];for(const dr of drawings)dr.spec_ids=[dr.spec_id,...links.filter(l=>l.drawing_id===dr.id).map(l=>l.spec_id)];
 const lines=p.lines.map((l,index)=>{if(l.due<p.date)throw Error('交期不可早於進貨日期');const s=specs.find(s=>s.id===l.spec_id);const dr=drawings.find(d=>d.id===l.drawing_id&&drawingMatches(d,l.spec_id));if(!s||l.drawing_id&&!dr)throw Error('圖面必須對應所選的客戶與來料規格');return {...l,position:index,id:`${id}:${index}`,s:JSON.parse(s.data),dr:dr?{...JSON.parse(dr.data),id:dr.id,number:dr.number,version:dr.version,file_name:dr.file_name}:null}});
 const receiptNumber=p.number||await nextReceiptNumber(p.customer_id,p.date);
 const docLines=lines.map(l=>({material:l.s.material,name:l.s.name,diameter:l.s.raw_diameter,spec:specLabel(l.s),qty:l.quantity,unit:'支',packages:l.packages,package_unit:l.package_unit,price:0}));
 await db.batch([db.prepare("INSERT INTO documents (id,number,kind,partner_id,date,lines,subtotal,tax,total,note,customer_id,barrels,original_number) VALUES (?,?,'in',?,?,?,0,0,0,?,?,?,?)").bind(id,receiptNumber,p.supplier_id,p.date,JSON.stringify(docLines),p.note,p.customer_id,p.barrels,p.number),db.prepare("INSERT INTO intakes (id,document_id,customer_id,spec_id,drawing_id,material_snapshot,drawing_snapshot,quantity,packages,package_unit,due,fee,dispatched,position) SELECT json_extract(value,'$.id'),?,?,json_extract(value,'$.spec_id'),NULLIF(json_extract(value,'$.drawing_id'),''),json_extract(value,'$.material_snapshot'),json_extract(value,'$.drawing_snapshot'),json_extract(value,'$.quantity'),json_extract(value,'$.packages'),json_extract(value,'$.package_unit'),json_extract(value,'$.due'),json_extract(value,'$.fee'),0,json_extract(value,'$.position') FROM json_each(?)").bind(id,p.customer_id,JSON.stringify(lines.map(l=>({...l,material_snapshot:JSON.stringify(l.s),drawing_snapshot:l.dr?JSON.stringify(l.dr):null,fee:Math.round(l.fee*100)})))),...barrelStatements(id,p.customer_id,p.date,p.barrels,'in'),db.prepare("DELETE FROM material_drafts WHERE id='receipt' AND json_extract(data,'$.request_id')=?").bind(id)]);
 }
 else if(b.action==='bind'){
 const p=z.object({id:text,drawing_id:text}).parse(b);const i=await db.prepare('SELECT * FROM intakes WHERE id=? AND dispatched=0').bind(p.id).first<any>();if(!i)throw Error('已派工的來料不可更換圖面');const dr=await db.prepare('SELECT * FROM drawings WHERE disabled=0 AND id=? AND customer_id=? AND (spec_id=? OR EXISTS(SELECT 1 FROM drawing_specs ds WHERE ds.drawing_id=drawings.id AND ds.spec_id=?))').bind(p.drawing_id,i.customer_id,i.spec_id,i.spec_id).first<any>();if(!dr)throw Error('圖面與客戶、來料不相符');const snapshot={...JSON.parse(dr.data),id:dr.id,number:dr.number,version:dr.version,file_name:dr.file_name};const r=await db.prepare('UPDATE intakes SET drawing_id=?,drawing_snapshot=? WHERE id=? AND dispatched=0').bind(dr.id,JSON.stringify(snapshot),p.id).run();if(!r.meta.changes)throw Error('此筆已派工，請重新整理');
 }
 else if(b.action==='terms'){
 const p=z.object({id:text,fee:z.number().nonnegative().max(10000000),due:day}).parse(b);const i=await db.prepare('SELECT d.date FROM intakes i JOIN documents d ON d.id=i.document_id WHERE i.id=?').bind(p.id).first<{date:string}>();if(!i||p.due<i.date)throw Error('交期不可早於進貨日期');const r=await db.prepare('UPDATE intakes SET fee=?,due=? WHERE id=? AND dispatched=0').bind(Math.round(p.fee*100),p.due,p.id).run();if(!r.meta.changes)throw Error('已派工，不能修改本批加工條件');
 }
 else if(b.action==='dispatch'){
 const p=z.object({id:text,machine:text,operator:text}).parse(b);const i=await db.prepare('SELECT i.*,d.date FROM intakes i JOIN documents d ON d.id=i.document_id WHERE i.id=? AND d.voided=0').bind(p.id).first<any>();if(!i||!i.drawing_snapshot)throw Error('請先確認這筆來料的加工圖面');
 if(await db.prepare('SELECT id FROM intake_allocations WHERE intake_id=?').bind(p.id).first())throw Error('此筆已有加工分配，請從分配明細派工');
 const existing=await db.prepare('SELECT id FROM work_orders WHERE intake_id=?').bind(p.id).first<any>();if(existing)return Response.json({ok:true,id:existing.id});
 const raw=JSON.parse(i.material_snapshot);const dr=JSON.parse(i.drawing_snapshot);if(!drawingReady(dr))throw Error('圖面兩端尚待確認，請確認後另存版本再派工');
 // Internal compatibility record is created automatically; users never re-enter an order.
 await db.batch([
 db.prepare('INSERT INTO sales_orders (id,number,partner_id,date,due,product,spec,quantity,unit,price,note) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM intakes WHERE id=? AND dispatched=0 AND NOT EXISTS(SELECT 1 FROM intake_allocations WHERE intake_id=intakes.id) AND drawing_snapshot=? AND EXISTS(SELECT 1 FROM documents WHERE id=intakes.document_id AND voided=0))').bind(i.id,`SRC-${i.id}`,i.customer_id,i.date,i.due,raw.name,`${raw.drive} × ${raw.size} × ${raw.profile} · ${drawingSummary(dr)}`,i.quantity,'支',i.fee,`圖號 ${dr.number} / ${dr.version}；${dr.note||''}`,i.id,i.drawing_snapshot),
 db.prepare("INSERT INTO work_orders (id,number,order_id,machine,operator,status,good,defective,shipped,intake_id) SELECT ?,?,?,?,?, 'pending',0,0,0,? WHERE EXISTS(SELECT 1 FROM sales_orders WHERE id=?)").bind(id,no('WO'),i.id,p.machine,p.operator,i.id,i.id),
 db.prepare('UPDATE intakes SET dispatched=1 WHERE id=? AND EXISTS(SELECT 1 FROM work_orders WHERE id=?)').bind(i.id,id)]);
 if(!await db.prepare('SELECT id FROM work_orders WHERE id=?').bind(id).first())throw Error('來料圖面或派工狀態已改變，請重新整理');
 }
 else throw Error('不支援此操作');return Response.json({ok:true,id});
 }catch(e){if(uploaded)try{await bucket().delete(uploaded)}catch{}console.error(e);return Response.json({error:e instanceof z.ZodError?'請檢查必填欄位、日期及數值。':e instanceof Error&&!/D1|SQLITE|constraint/i.test(e.message)?e.message:'儲存未完成，請檢查編號是否重複，或重新整理後再試。'},{status:400})}}
