import {database} from '@/db/raw';
import {z} from 'zod';
export async function GET(req:Request){if(!decodeURIComponent(req.headers.get('oai-authenticated-user-id')||''))return Response.json({error:'請先登入'},{status:401});try{const db=database(),before=new URL(req.url).searchParams.get('before');const audit=(await db.prepare('SELECT rowid AS sequence,* FROM operation_audit WHERE (? IS NULL OR rowid<?) ORDER BY rowid DESC LIMIT 100').bind(before,before).all()).results;const trash=(await db.prepare("SELECT a.* FROM operation_audit a WHERE a.table_name='intake_allocations' AND a.action='delete' AND NOT EXISTS(SELECT 1 FROM intake_allocations i WHERE i.id=a.record_id) AND a.rowid=(SELECT MAX(b.rowid) FROM operation_audit b WHERE b.table_name=a.table_name AND b.record_id=a.record_id AND b.action='delete') ORDER BY a.rowid DESC LIMIT 100").all()).results;return Response.json({audit,trash},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'操作紀錄讀取失敗'},{status:503})}}
export async function POST(req:Request){try{
 if(!decodeURIComponent(req.headers.get('oai-authenticated-user-id')||''))return Response.json({error:'請先登入'},{status:401});if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'請從本站操作'},{status:403});
 const p=z.object({audit_id:z.string().min(1),reason:z.string().trim().min(1).max(200)}).parse(await req.json());const db=database(req);
 const audit=await db.prepare("SELECT * FROM operation_audit WHERE id=? AND table_name='intake_allocations' AND action='delete'").bind(p.audit_id).first<any>();if(!audit)throw Error('找不到可復原項目');const a=JSON.parse(audit.before);
 if(await db.prepare('SELECT id FROM intake_allocations WHERE id=?').bind(a.id).first())return Response.json({ok:true});
 const latest=await db.prepare("SELECT id FROM operation_audit WHERE table_name='intake_allocations' AND record_id=? AND action='delete' ORDER BY rowid DESC LIMIT 1").bind(a.id).first<any>();if(latest?.id!==p.audit_id)throw Error('已有較新的移除紀錄，請重新整理');
 const result=await db.batch([db.prepare(`INSERT INTO intake_allocations(id,intake_id,drawing_id,drawing_snapshot,quantity,fee,due,created_at) SELECT ?,i.id,?,?,?,?,?,? FROM intakes i JOIN documents d ON d.id=i.document_id JOIN drawings dr ON dr.id=? WHERE i.id=? AND d.voided=0 AND dr.disabled=0 AND dr.customer_id=i.customer_id AND (dr.spec_id=i.spec_id OR EXISTS(SELECT 1 FROM drawing_specs s WHERE s.drawing_id=dr.id AND s.spec_id=i.spec_id)) AND NOT EXISTS(SELECT 1 FROM work_orders w WHERE w.intake_id=i.id AND w.allocation_id IS NULL) AND (SELECT id FROM operation_audit WHERE table_name='intake_allocations' AND record_id=? AND action='delete' ORDER BY rowid DESC LIMIT 1)=? AND i.quantity-COALESCE((SELECT SUM(quantity) FROM intake_allocations WHERE intake_id=i.id),0)>=?`).bind(a.id,a.drawing_id,a.drawing_snapshot,a.quantity,a.fee,a.due,a.created_at,a.drawing_id,a.intake_id,a.id,p.audit_id,a.quantity),db.prepare("INSERT INTO operation_audit(id,stamp,actor,table_name,record_id,action,before,after) SELECT ?,?,?, 'intake_allocations',?,'restore',?,? WHERE EXISTS(SELECT 1 FROM intake_allocations WHERE id=?)").bind(crypto.randomUUID(),new Date().toISOString(),JSON.stringify({id:decodeURIComponent(req.headers.get('oai-authenticated-user-id')||''),email:decodeURIComponent(req.headers.get('oai-authenticated-user-email')||'')}),a.id,JSON.stringify({reason:p.reason,source:p.audit_id}),JSON.stringify(a),a.id)]);
 if(!result[0].meta.changes)throw Error('無法復原：請檢查剩餘數量、規格是否變更、圖面停用或單据作廢');return Response.json({ok:true});
 }catch(e){return Response.json({error:e instanceof z.ZodError?'請填寫復原原因':e instanceof Error?e.message:'復原失敗'},{status:400})}}
